/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AmdDetailRecord {
    /**
    * Feature invocation id
    */
    'id'?: string;
    /**
    * Feature invocation time
    */
    'invokedAt'?: Date;
    /**
    * Feature name
    */
    'feature'?: AmdDetailRecordFeatureEnum;
    /**
    * User-provided tags
    */
    'tags'?: string;
    /**
    * Billing Group id
    */
    'billingGroupId'?: string;
    /**
    * Name of the Billing Group specified in billing_group_id
    */
    'billingGroupName'?: string;
    /**
    * Connection id
    */
    'connectionId'?: string;
    /**
    * Connection name
    */
    'connectionName'?: string;
    /**
    * Telnyx UUID that identifies the related call leg
    */
    'callLegId'?: string;
    /**
    * Telnyx UUID that identifies the related call session
    */
    'callSessionId'?: string;
    /**
    * Indicates whether Telnyx billing charges might be applicable
    */
    'isTelnyxBillable'?: boolean;
    /**
    * Currency amount per billing unit used to calculate the Telnyx billing cost
    */
    'rate'?: string;
    /**
    * Billing unit used to calculate the Telnyx billing cost
    */
    'rateMeasuredIn'?: string;
    /**
    * Currency amount for Telnyx billing cost
    */
    'cost'?: string;
    /**
    * Telnyx account currency used to describe monetary values, including billing cost
    */
    'currency'?: string;
    'recordType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "invokedAt",
            "baseName": "invoked_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "feature",
            "baseName": "feature",
            "type": "AmdDetailRecordFeatureEnum",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingGroupId",
            "baseName": "billing_group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingGroupName",
            "baseName": "billing_group_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionName",
            "baseName": "connection_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "callLegId",
            "baseName": "call_leg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "callSessionId",
            "baseName": "call_session_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isTelnyxBillable",
            "baseName": "is_telnyx_billable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "string",
            "format": ""
        },
        {
            "name": "rateMeasuredIn",
            "baseName": "rate_measured_in",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AmdDetailRecord.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AmdDetailRecordFeatureEnum = "PREMIUM" ;

