/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class BillingGroup {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: BillingGroupRecordTypeEnum;
    /**
    * Identifies the type of resource.
    */
    'id'?: string;
    /**
    * Identifies the organization that owns the resource.
    */
    'organizationId'?: string;
    /**
    * A user-specified name for the billing group
    */
    'name'?: string;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: Date;
    /**
    * ISO 8601 formatted date indicating when the resource was updated.
    */
    'updatedAt'?: Date;
    /**
    * ISO 8601 formatted date indicating when the resource was removed.
    */
    'deletedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "BillingGroupRecordTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "organizationId",
            "baseName": "organization_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return BillingGroup.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BillingGroupRecordTypeEnum = "billing_group" ;

