/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SoleProprietorData } from '../models/SoleProprietorData.ts';
import { HttpFile } from '../http/http.ts';

export class BulkCreationRequest {
    'brands': Array<SoleProprietorData>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "brands",
            "baseName": "brands",
            "type": "Array<SoleProprietorData>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkCreationRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

