/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BulkCreationStatusResponse } from '../models/BulkCreationStatusResponse.ts';
import { CampaignRegistryApiSchemasBulkCreationMeta } from '../models/CampaignRegistryApiSchemasBulkCreationMeta.ts';
import { HttpFile } from '../http/http.ts';

export class BulkCreationTasksResponse {
    'meta': CampaignRegistryApiSchemasBulkCreationMeta;
    'records': Array<BulkCreationStatusResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "CampaignRegistryApiSchemasBulkCreationMeta",
            "format": ""
        },
        {
            "name": "records",
            "baseName": "records",
            "type": "Array<BulkCreationStatusResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkCreationTasksResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

