/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BusinessIdentityAddress } from '../models/BusinessIdentityAddress.ts';
import { BusinessIdentityContactsInner } from '../models/BusinessIdentityContactsInner.ts';
import { HttpFile } from '../http/http.ts';

export class BusinessIdentity {
    'recordType'?: string;
    'id'?: string;
    /**
    * The ID of the organization that owns the record
    */
    'organizationId'?: string;
    /**
    * The name of the business identity on the telnyx platform
    */
    'name'?: string;
    /**
    * The email of the business
    */
    'businessEmail'?: string;
    /**
    * The name of the business
    */
    'businessName'?: string;
    'businessPhoneNumber'?: string;
    'businessDescription'?: string;
    /**
    * User acceptance of the terms of submission
    */
    'submissionAcknowledgement'?: boolean;
    'websiteUrl'?: Array<string>;
    'address'?: BusinessIdentityAddress;
    'contacts'?: Array<BusinessIdentityContactsInner>;
    /**
    * An ISO 8601 datetime string for when the business identity was added to the Telnyx platform
    */
    'createdAt'?: string;
    /**
    * An ISO 8601 datetime string for when the business identity was updated
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "organizationId",
            "baseName": "organization_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessEmail",
            "baseName": "business_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessName",
            "baseName": "business_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessPhoneNumber",
            "baseName": "business_phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessDescription",
            "baseName": "business_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "submissionAcknowledgement",
            "baseName": "submission_acknowledgement",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "websiteUrl",
            "baseName": "website_url",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "BusinessIdentityAddress",
            "format": ""
        },
        {
            "name": "contacts",
            "baseName": "contacts",
            "type": "Array<BusinessIdentityContactsInner>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return BusinessIdentity.attributeTypeMap;
    }

    public constructor() {
    }
}

