/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CallRequestAnsweringMachineDetectionConfig } from '../models/CallRequestAnsweringMachineDetectionConfig.ts';
import { CallRequestTo } from '../models/CallRequestTo.ts';
import { CustomSipHeader } from '../models/CustomSipHeader.ts';
import { DialogflowConfig } from '../models/DialogflowConfig.ts';
import { SipHeader } from '../models/SipHeader.ts';
import { SoundModifications } from '../models/SoundModifications.ts';
import { HttpFile } from '../http/http.ts';

export class CallRequest {
    'to': CallRequestTo;
    /**
    * The `from` number to be used as the caller id presented to the destination (`to` number). The number should be in +E164 format.
    */
    '_from': string;
    /**
    * The `from_display_name` string to be used as the caller id name (SIP From Display Name) presented to the destination (`to` number). The string should have a maximum of 128 characters, containing only letters, numbers, spaces, and -_~!.+ special characters. If ommited, the display name will be the same as the number in the `from` field.
    */
    'fromDisplayName'?: string;
    /**
    * The ID of the Call Control App (formerly ID of the connection) to be used when dialing the destination.
    */
    'connectionId': string;
    /**
    * The URL of a file to be played back to the callee when the call is answered. The URL can point to either a WAV or MP3 file. media_name and audio_url cannot be used together in one request.
    */
    'audioUrl'?: string;
    /**
    * The media_name of a file to be played back to the callee when the call is answered. The media_name must point to a file previously uploaded to api.telnyx.com/v2/media by the same user/organization. The file must either be a WAV or MP3 file.
    */
    'mediaName'?: string;
    /**
    * The list of comma-separated codecs in a preferred order for the forked media to be received.
    */
    'preferredCodecs'?: string;
    /**
    * The number of seconds that Telnyx will wait for the call to be answered by the destination to which it is being called. If the timeout is reached before an answer is received, the call will hangup and a `call.hangup` webhook with a `hangup_cause` of `timeout` will be sent. Minimum value is 5 seconds. Maximum value is 120 seconds.
    */
    'timeoutSecs'?: number;
    /**
    * Sets the maximum duration of a Call Control Leg in seconds. If the time limit is reached, the call will hangup and a `call.hangup` webhook with a `hangup_cause` of `time_limit` will be sent. For example, by setting a time limit of 120 seconds, a Call Leg will be automatically terminated two minutes after being answered. The default time limit is 14400 seconds or 4 hours and this is also the maximum allowed call length.
    */
    'timeLimitSecs'?: number;
    /**
    * Enables Answering Machine Detection. Telnyx offers Premium and Standard detections. With Premium detection, when a call is answered, Telnyx runs real-time detection and sends a `call.machine.premium.detection.ended` webhook with one of the following results: `human_residence`, `human_business`, `machine`, `silence` or `fax_detected`. If we detect a beep, we also send a `call.machine.premium.greeting.ended` webhook with the result of `beep_detected`. If we detect a beep before `call.machine.premium.detection.ended` we only send `call.machine.premium.greeting.ended`, and if we detect a beep after `call.machine.premium.detection.ended`, we send both webhooks. With Standard detection, when a call is answered, Telnyx runs real-time detection to determine if it was picked up by a human or a machine and sends an `call.machine.detection.ended` webhook with the analysis result. If `greeting_end` or `detect_words` is used and a `machine` is detected, you will receive another `call.machine.greeting.ended` webhook when the answering machine greeting ends with a beep or silence. If `detect_beep` is used, you will only receive `call.machine.greeting.ended` if a beep is detected.
    */
    'answeringMachineDetection'?: CallRequestAnsweringMachineDetectionEnum;
    'answeringMachineDetectionConfig'?: CallRequestAnsweringMachineDetectionConfig;
    /**
    * Custom headers to be added to the SIP INVITE.
    */
    'customHeaders'?: Array<CustomSipHeader>;
    /**
    * Use this field to set the Billing Group ID for the call. Must be a valid and existing Billing Group ID.
    */
    'billingGroupId'?: string;
    /**
    * Use this field to add state to every subsequent webhook. It must be a valid Base-64 encoded string.
    */
    'clientState'?: string;
    /**
    * Use this field to avoid duplicate commands. Telnyx will ignore others Dial commands with the same `command_id`.
    */
    'commandId'?: string;
    /**
    * Use another call\'s control id for sharing the same call session id
    */
    'linkTo'?: string;
    /**
    * SIP Authentication username used for SIP challenges.
    */
    'sipAuthUsername'?: string;
    /**
    * SIP Authentication password used for SIP challenges.
    */
    'sipAuthPassword'?: string;
    /**
    * SIP headers to be added to the SIP INVITE request. Currently only User-to-User header is supported.
    */
    'sipHeaders'?: Array<SipHeader>;
    'soundModifications'?: SoundModifications;
    /**
    * The destination WebSocket address where the stream is going to be delivered.
    */
    'streamUrl'?: string;
    /**
    * Specifies which track should be streamed.
    */
    'streamTrack'?: CallRequestStreamTrackEnum;
    /**
    * Generate silence RTP packets when no transmission available.
    */
    'sendSilenceWhenIdle'?: boolean;
    /**
    * Use this field to override the URL for which Telnyx will send subsequent webhooks to for this call.
    */
    'webhookUrl'?: string;
    /**
    * HTTP request type used for `webhook_url`.
    */
    'webhookUrlMethod'?: CallRequestWebhookUrlMethodEnum;
    /**
    * Start recording automatically after an event. Disabled by default.
    */
    'record'?: CallRequestRecordEnum;
    /**
    * Defines which channel should be recorded (\'single\' or \'dual\') when `record` is specified.
    */
    'recordChannels'?: CallRequestRecordChannelsEnum;
    /**
    * Defines the format of the recording (\'wav\' or \'mp3\') when `record` is specified.
    */
    'recordFormat'?: CallRequestRecordFormatEnum;
    /**
    * Defines the maximum length for the recording in seconds when `record` is specified. The minimum value is 0. The maximum value is 43200. The default value is 0 (infinite).
    */
    'recordMaxLength'?: number;
    /**
    * The number of seconds that Telnyx will wait for the recording to be stopped if silence is detected when `record` is specified. The timer only starts when the speech is detected. The minimum value is 0. The default value is 0 (infinite).
    */
    'recordTimeoutSecs'?: number;
    /**
    * Enables Dialogflow for the current call. The default value is false.
    */
    'enableDialogflow'?: boolean;
    'dialogflowConfig'?: DialogflowConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "to",
            "baseName": "to",
            "type": "CallRequestTo",
            "format": ""
        },
        {
            "name": "_from",
            "baseName": "from",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromDisplayName",
            "baseName": "from_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "audioUrl",
            "baseName": "audio_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediaName",
            "baseName": "media_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferredCodecs",
            "baseName": "preferred_codecs",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeoutSecs",
            "baseName": "timeout_secs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeLimitSecs",
            "baseName": "time_limit_secs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "answeringMachineDetection",
            "baseName": "answering_machine_detection",
            "type": "CallRequestAnsweringMachineDetectionEnum",
            "format": ""
        },
        {
            "name": "answeringMachineDetectionConfig",
            "baseName": "answering_machine_detection_config",
            "type": "CallRequestAnsweringMachineDetectionConfig",
            "format": ""
        },
        {
            "name": "customHeaders",
            "baseName": "custom_headers",
            "type": "Array<CustomSipHeader>",
            "format": ""
        },
        {
            "name": "billingGroupId",
            "baseName": "billing_group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "clientState",
            "baseName": "client_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "commandId",
            "baseName": "command_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkTo",
            "baseName": "link_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "sipAuthUsername",
            "baseName": "sip_auth_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "sipAuthPassword",
            "baseName": "sip_auth_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "sipHeaders",
            "baseName": "sip_headers",
            "type": "Array<SipHeader>",
            "format": ""
        },
        {
            "name": "soundModifications",
            "baseName": "sound_modifications",
            "type": "SoundModifications",
            "format": ""
        },
        {
            "name": "streamUrl",
            "baseName": "stream_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "streamTrack",
            "baseName": "stream_track",
            "type": "CallRequestStreamTrackEnum",
            "format": ""
        },
        {
            "name": "sendSilenceWhenIdle",
            "baseName": "send_silence_when_idle",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookUrlMethod",
            "baseName": "webhook_url_method",
            "type": "CallRequestWebhookUrlMethodEnum",
            "format": ""
        },
        {
            "name": "record",
            "baseName": "record",
            "type": "CallRequestRecordEnum",
            "format": ""
        },
        {
            "name": "recordChannels",
            "baseName": "record_channels",
            "type": "CallRequestRecordChannelsEnum",
            "format": ""
        },
        {
            "name": "recordFormat",
            "baseName": "record_format",
            "type": "CallRequestRecordFormatEnum",
            "format": ""
        },
        {
            "name": "recordMaxLength",
            "baseName": "record_max_length",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "recordTimeoutSecs",
            "baseName": "record_timeout_secs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "enableDialogflow",
            "baseName": "enable_dialogflow",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dialogflowConfig",
            "baseName": "dialogflow_config",
            "type": "DialogflowConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CallRequestAnsweringMachineDetectionEnum = "premium" | "detect" | "detect_beep" | "detect_words" | "greeting_end" | "disabled" ;
export type CallRequestStreamTrackEnum = "inbound_track" | "outbound_track" | "both_tracks" ;
export type CallRequestWebhookUrlMethodEnum = "POST" | "GET" ;
export type CallRequestRecordEnum = "record-from-answer" ;
export type CallRequestRecordChannelsEnum = "single" | "dual" ;
export type CallRequestRecordFormatEnum = "wav" | "mp3" ;

