/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CallEvent {
    'recordType': CallEventRecordTypeEnum;
    /**
    * Uniquely identifies an individual call leg.
    */
    'callLegId': string;
    /**
    * Uniquely identifies the call control session. A session may include multiple call leg events.
    */
    'callSessionId': string;
    /**
    * Event timestamp
    */
    'eventTimestamp': string;
    /**
    * Event name
    */
    'name': string;
    /**
    * Event type
    */
    'type': CallEventTypeEnum;
    /**
    * Event metadata, which includes raw event, and extra information based on event type
    */
    'metadata': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "CallEventRecordTypeEnum",
            "format": ""
        },
        {
            "name": "callLegId",
            "baseName": "call_leg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "callSessionId",
            "baseName": "call_session_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventTimestamp",
            "baseName": "event_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CallEventTypeEnum",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallEvent.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CallEventRecordTypeEnum = "call_event" ;
export type CallEventTypeEnum = "command" | "webhook" ;

