/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Call {
    'recordType': CallRecordTypeEnum;
    /**
    * ID that is unique to the call session and can be used to correlate webhook events. Call session is a group of related call legs that logically belong to the same phone call, e.g. an inbound and outbound leg of a transferred call
    */
    'callSessionId': string;
    /**
    * ID that is unique to the call and can be used to correlate webhook events
    */
    'callLegId': string;
    /**
    * Unique identifier and token for controlling the call.
    */
    'callControlId': string;
    /**
    * Indicates whether the call is alive or not. For Dial command it will always be `false` (dialing is asynchronous).
    */
    'isAlive': boolean;
    /**
    * State received from a command.
    */
    'clientState'?: string;
    /**
    * Indicates the duration of the call in seconds
    */
    'callDuration'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "CallRecordTypeEnum",
            "format": ""
        },
        {
            "name": "callSessionId",
            "baseName": "call_session_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "callLegId",
            "baseName": "call_leg_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "callControlId",
            "baseName": "call_control_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isAlive",
            "baseName": "is_alive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clientState",
            "baseName": "client_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "callDuration",
            "baseName": "call_duration",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Call.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CallRecordTypeEnum = "call" ;

