/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CallReferFailedPayload } from '../models/CallReferFailedPayload.ts';
import { HttpFile } from '../http/http.ts';

export class CallReferFailed {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: CallReferFailedRecordTypeEnum;
    /**
    * The type of event being delivered.
    */
    'eventType'?: CallReferFailedEventTypeEnum;
    /**
    * Identifies the type of resource.
    */
    'id'?: string;
    /**
    * ISO 8601 datetime of when the event occurred.
    */
    'occurredAt'?: Date;
    'payload'?: CallReferFailedPayload;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "CallReferFailedRecordTypeEnum",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "CallReferFailedEventTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "occurredAt",
            "baseName": "occurred_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "CallReferFailedPayload",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallReferFailed.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CallReferFailedRecordTypeEnum = "event" ;
export type CallReferFailedEventTypeEnum = "call.refer.failed" ;

