/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CallbackWebhookMeta {
    /**
    * The number of times the callback webhook has been attempted.
    */
    'attempt'?: number;
    /**
    * The URL that the callback webhook was delivered to.
    */
    'deliveredTo'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attempt",
            "baseName": "attempt",
            "type": "number",
            "format": ""
        },
        {
            "name": "deliveredTo",
            "baseName": "delivered_to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallbackWebhookMeta.attributeTypeMap;
    }

    public constructor() {
    }
}

