/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CampaignSharingStatus } from '../models/CampaignSharingStatus.ts';
import { HttpFile } from '../http/http.ts';

export class CampaignSharingChain {
    'sharedByMe'?: CampaignSharingStatus;
    'sharedWithMe'?: CampaignSharingStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sharedByMe",
            "baseName": "sharedByMe",
            "type": "CampaignSharingStatus",
            "format": ""
        },
        {
            "name": "sharedWithMe",
            "baseName": "sharedWithMe",
            "type": "CampaignSharingStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CampaignSharingChain.attributeTypeMap;
    }

    public constructor() {
    }
}

