/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Carrier {
    /**
    * Region code that matches the specific country calling code if the requested phone number type is mobile
    */
    'mobileCountryCode'?: string;
    /**
    * National destination code (NDC), with a 0 prefix, if an NDC is found and the requested phone number type is mobile
    */
    'mobileNetworkCode'?: string;
    /**
    * SPID (Service Provider ID) name, if the requested phone number has been ported; otherwise, the name of carrier who owns the phone number block
    */
    'name'?: string;
    /**
    * A phone number type that identifies the type of service associated with the requested phone number
    */
    'type'?: CarrierTypeEnum;
    /**
    * Unused
    */
    'errorCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mobileCountryCode",
            "baseName": "mobile_country_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobileNetworkCode",
            "baseName": "mobile_network_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CarrierTypeEnum",
            "format": ""
        },
        {
            "name": "errorCode",
            "baseName": "error_code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Carrier.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CarrierTypeEnum = "fixed line" | "mobile" | "voip" | "fixed line or mobile" | "toll free" | "premium rate" | "shared cost" | "personal number" | "pager" | "uan" | "voicemail" | "unknown" ;

