/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CompositionCompletedPayload {
    /**
    * Composition ID that identifies the room composition.
    */
    'compositionId'?: string;
    /**
    * Url to download the room composition.
    */
    'downloadUrl'?: string;
    /**
    * Room composition duration in seconds.
    */
    'durationSecs'?: number;
    /**
    * Format of the room composition.
    */
    'format'?: string;
    /**
    * Format of the room composition.
    */
    'resolution'?: string;
    /**
    * Room ID associated with the room composition.
    */
    'roomId'?: string;
    /**
    * Session ID associated with the room composition.
    */
    'sessionId'?: string;
    /**
    * Room composition size in MB.
    */
    'sizeMb'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "compositionId",
            "baseName": "composition_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "downloadUrl",
            "baseName": "download_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "durationSecs",
            "baseName": "duration_secs",
            "type": "number",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string",
            "format": ""
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "string",
            "format": ""
        },
        {
            "name": "roomId",
            "baseName": "room_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sessionId",
            "baseName": "session_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sizeMb",
            "baseName": "size_mb",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return CompositionCompletedPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

