/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConferenceCreatedPayload } from '../models/ConferenceCreatedPayload.ts';
import { HttpFile } from '../http/http.ts';

export class ConferenceCreated {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: ConferenceCreatedRecordTypeEnum;
    /**
    * The type of event being delivered.
    */
    'eventType'?: ConferenceCreatedEventTypeEnum;
    /**
    * Identifies the type of resource.
    */
    'id'?: string;
    'payload'?: ConferenceCreatedPayload;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "ConferenceCreatedRecordTypeEnum",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "ConferenceCreatedEventTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "ConferenceCreatedPayload",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConferenceCreated.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ConferenceCreatedRecordTypeEnum = "event" ;
export type ConferenceCreatedEventTypeEnum = "conference.created" ;

