/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ConnectionRtcpSettings {
    /**
    * RTCP port by default is rtp+1, it can also be set to rtcp-mux
    */
    'port'?: ConnectionRtcpSettingsPortEnum;
    /**
    * BETA - Enable the capture and storage of RTCP messages to create QoS reports on the Telnyx Mission Control Portal.
    */
    'captureEnabled'?: boolean;
    /**
    * RTCP reports are sent to customers based on the frequency set. Frequency is in seconds and it can be set to values from 5 to 3000 seconds.
    */
    'reportFrequencySecs'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "port",
            "baseName": "port",
            "type": "ConnectionRtcpSettingsPortEnum",
            "format": ""
        },
        {
            "name": "captureEnabled",
            "baseName": "capture_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reportFrequencySecs",
            "baseName": "report_frequency_secs",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectionRtcpSettings.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ConnectionRtcpSettingsPortEnum = "rtcp-mux" | "rtp+1" ;

