/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Audio } from '../models/Audio.ts';
import { Document } from '../models/Document.ts';
import { Image } from '../models/Image.ts';
import { Location } from '../models/Location.ts';
import { MessageType } from '../models/MessageType.ts';
import { Template } from '../models/Template.ts';
import { Text } from '../models/Text.ts';
import { Video } from '../models/Video.ts';
import { HttpFile } from '../http/http.ts';

export class CreateWhatsAppMessageRequest {
    /**
    * The sender\'s WhatsApp ID.
    */
    'whatsappUserId': string;
    /**
    * The WhatsApp ID (phone number) returned from contacts endpoint.
    */
    'to': string;
    'type'?: MessageType;
    'text'?: Text;
    'audio'?: Audio;
    'image'?: Image;
    'document'?: Document;
    'video'?: Video;
    'location'?: Location;
    /**
    * Specifying preview_url in the request is optional when not including a URL in your message. To include a URL preview, set preview_url to true in the message body and make sure the URL begins with http:// or https://.
    */
    'previewUrl'?: boolean;
    'template'?: Template;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "whatsappUserId",
            "baseName": "whatsapp_user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MessageType",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "Text",
            "format": ""
        },
        {
            "name": "audio",
            "baseName": "audio",
            "type": "Audio",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "Image",
            "format": ""
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "Document",
            "format": ""
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "Video",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "previewUrl",
            "baseName": "preview_url",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Template",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateWhatsAppMessageRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



