/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NumberPoolSettings } from '../models/NumberPoolSettings.ts';
import { UrlShortenerSettings } from '../models/UrlShortenerSettings.ts';
import { HttpFile } from '../http/http.ts';

export class CreateMessagingProfileRequest {
    /**
    * A user friendly name for the messaging profile.
    */
    'name': string;
    /**
    * Specifies whether the messaging profile is enabled or not.
    */
    'enabled'?: boolean;
    /**
    * The URL where webhooks related to this messaging profile will be sent.
    */
    'webhookUrl'?: string | null;
    /**
    * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
    */
    'webhookFailoverUrl'?: string | null;
    /**
    * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
    */
    'webhookApiVersion'?: CreateMessagingProfileRequestWebhookApiVersionEnum;
    'numberPoolSettings'?: NumberPoolSettings | null;
    'urlShortenerSettings'?: UrlShortenerSettings | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookFailoverUrl",
            "baseName": "webhook_failover_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookApiVersion",
            "baseName": "webhook_api_version",
            "type": "CreateMessagingProfileRequestWebhookApiVersionEnum",
            "format": ""
        },
        {
            "name": "numberPoolSettings",
            "baseName": "number_pool_settings",
            "type": "NumberPoolSettings",
            "format": ""
        },
        {
            "name": "urlShortenerSettings",
            "baseName": "url_shortener_settings",
            "type": "UrlShortenerSettings",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateMessagingProfileRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateMessagingProfileRequestWebhookApiVersionEnum = "1" | "2" | "2010-04-01" ;

