/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CreateShortCodeMessageRequest {
    /**
    * Phone number, in +E.164 format, used to send the message.
    */
    '_from': string;
    /**
    * Receiving address (+E.164 formatted phone number or short code).
    */
    'to': string;
    /**
    * Message body (i.e., content) as a non-empty string.  **Required for SMS**
    */
    'text'?: string;
    /**
    * Subject of multimedia message
    */
    'subject'?: string;
    /**
    * A list of media URLs. The total media size must be less than 1 MB.  **Required for MMS**
    */
    'mediaUrls'?: Array<string>;
    /**
    * The URL where webhooks related to this message will be sent.
    */
    'webhookUrl'?: string;
    /**
    * The failover URL where webhooks related to this message will be sent if sending to the primary URL fails.
    */
    'webhookFailoverUrl'?: string;
    /**
    * If the profile this number is associated with has webhooks, use them for delivery notifications. If webhooks are also specified on the message itself, they will be attempted first, then those on the profile.
    */
    'useProfileWebhooks'?: boolean;
    /**
    * The protocol for sending the message, either SMS or MMS.
    */
    'type'?: CreateShortCodeMessageRequestTypeEnum;
    /**
    * Automatically detect if an SMS message is unusually long and exceeds a recommended limit of message parts.
    */
    'autoDetect'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_from",
            "baseName": "from",
            "type": "string",
            "format": "address"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": "address"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediaUrls",
            "baseName": "media_urls",
            "type": "Array<string>",
            "format": "url"
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookFailoverUrl",
            "baseName": "webhook_failover_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "useProfileWebhooks",
            "baseName": "use_profile_webhooks",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CreateShortCodeMessageRequestTypeEnum",
            "format": ""
        },
        {
            "name": "autoDetect",
            "baseName": "auto_detect",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateShortCodeMessageRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateShortCodeMessageRequestTypeEnum = "SMS" | "MMS" ;

