/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CreateFaxApplicationRequestInbound {
    /**
    * When set, this will limit the number of concurrent inbound calls to phone numbers associated with this connection.
    */
    'channelLimit'?: number;
    /**
    * Specifies a subdomain that can be used to receive Inbound calls to a Connection, in the same way a phone number is used, from a SIP endpoint. Example: the subdomain \"example.sip.telnyx.com\" can be called from any SIP endpoint by using the SIP URI \"sip:@example.sip.telnyx.com\" where the user part can be any alphanumeric value. Please note TLS encrypted calls are not allowed for subdomain calls.
    */
    'sipSubdomain'?: string;
    /**
    * This option can be enabled to receive calls from: \"Anyone\" (any SIP endpoint in the public Internet) or \"Only my connections\" (any connection assigned to the same Telnyx user).
    */
    'sipSubdomainReceiveSettings'?: CreateFaxApplicationRequestInboundSipSubdomainReceiveSettingsEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelLimit",
            "baseName": "channel_limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "sipSubdomain",
            "baseName": "sip_subdomain",
            "type": "string",
            "format": ""
        },
        {
            "name": "sipSubdomainReceiveSettings",
            "baseName": "sip_subdomain_receive_settings",
            "type": "CreateFaxApplicationRequestInboundSipSubdomainReceiveSettingsEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateFaxApplicationRequestInbound.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateFaxApplicationRequestInboundSipSubdomainReceiveSettingsEnum = "only_my_connections" | "from_anyone" ;

