/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Cursor } from '../models/Cursor.ts';
import { HttpFile } from '../http/http.ts';

export class CursorPaginationMeta {
    'cursors'?: Cursor;
    'totalItems'?: number;
    /**
    * Path to next page.
    */
    'next'?: string;
    /**
    * Path to previous page.
    */
    'previous'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cursors",
            "baseName": "cursors",
            "type": "Cursor",
            "format": ""
        },
        {
            "name": "totalItems",
            "baseName": "total_items",
            "type": "number",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CursorPaginationMeta.attributeTypeMap;
    }

    public constructor() {
    }
}

