/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerServiceRecordResultAddress } from '../models/CustomerServiceRecordResultAddress.ts';
import { CustomerServiceRecordResultAdmin } from '../models/CustomerServiceRecordResultAdmin.ts';
import { HttpFile } from '../http/http.ts';

/**
* The result of the CSR request. This field would be null in case of `pending` or `failed` status.
*/
export class CustomerServiceRecordResult {
    /**
    * The name of the carrier that the customer service record is for.
    */
    'carrierName'?: string;
    /**
    * The associated phone numbers of the customer service record.
    */
    'associatedPhoneNumbers'?: Array<string>;
    'admin'?: CustomerServiceRecordResultAdmin;
    'address'?: CustomerServiceRecordResultAddress;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "carrierName",
            "baseName": "carrier_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "associatedPhoneNumbers",
            "baseName": "associated_phone_numbers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "CustomerServiceRecordResultAdmin",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "CustomerServiceRecordResultAddress",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerServiceRecordResult.attributeTypeMap;
    }

    public constructor() {
    }
}

