/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerServiceRecordStatusChangedEventPayload } from '../models/CustomerServiceRecordStatusChangedEventPayload.ts';
import { HttpFile } from '../http/http.ts';

export class CustomerServiceRecordStatusChangedEvent {
    /**
    * Uniquely identifies the callback event.
    */
    'id'?: string;
    /**
    * The type of the callback event.
    */
    'eventType'?: CustomerServiceRecordStatusChangedEventEventTypeEnum;
    'payload'?: CustomerServiceRecordStatusChangedEventPayload;
    /**
    * ISO 8601 formatted date indicating when the callback event occurred.
    */
    'occurredAt'?: Date;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: CustomerServiceRecordStatusChangedEventRecordTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "CustomerServiceRecordStatusChangedEventEventTypeEnum",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "CustomerServiceRecordStatusChangedEventPayload",
            "format": ""
        },
        {
            "name": "occurredAt",
            "baseName": "occurred_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "CustomerServiceRecordStatusChangedEventRecordTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerServiceRecordStatusChangedEvent.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CustomerServiceRecordStatusChangedEventEventTypeEnum = "customer_service_record.status_changed" ;
export type CustomerServiceRecordStatusChangedEventRecordTypeEnum = "event" ;

