/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Date/time by component
*/
export class DateTimeComponent {
    /**
    * Both strings and numbers are accepted. If different from the value derived from the date (if specified), use the derived value.
    */
    'dayOfWeek'?: DateTimeComponentDayOfWeekEnum;
    /**
    * The day of month
    */
    'dayOfMonth'?: number;
    /**
    * The year
    */
    'year'?: number;
    /**
    * The month
    */
    'month'?: number;
    /**
    * The hour
    */
    'hour'?: number;
    /**
    * The minute
    */
    'minute'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dayOfWeek",
            "baseName": "day_of_week",
            "type": "DateTimeComponentDayOfWeekEnum",
            "format": "int32"
        },
        {
            "name": "dayOfMonth",
            "baseName": "day_of_month",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hour",
            "baseName": "hour",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minute",
            "baseName": "minute",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return DateTimeComponent.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DateTimeComponentDayOfWeekEnum = "1" | "2" | "3" | "4" | "5" | "6" | "7" ;

