/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BrandStatus } from '../models/BrandStatus.ts';
import { CampaignStatus } from '../models/CampaignStatus.ts';
import { PhoneNumberStatus } from '../models/PhoneNumberStatus.ts';
import { HttpFile } from '../http/http.ts';

export class DetailedTaskStatus {
    /**
    * The ID of the task associated with bulk Sole Proprietor brand and campaign creation.
    */
    'taskId': string;
    /**
    * A user generated unique identifier that keeps track of sole proprietor brand/campaign combinations submitted during bulk creation.
    */
    'referenceId': string;
    /**
    * The status of the individual brand submitted via bulk creation.
    */
    'brand': Array<BrandStatus>;
    /**
    * The status of the individual campaign submitted via bulk creation.
    */
    'campaign': Array<CampaignStatus>;
    'phoneNumbers': Array<PhoneNumberStatus>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "string",
            "format": ""
        },
        {
            "name": "referenceId",
            "baseName": "referenceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "brand",
            "baseName": "brand",
            "type": "Array<BrandStatus>",
            "format": ""
        },
        {
            "name": "campaign",
            "baseName": "campaign",
            "type": "Array<CampaignStatus>",
            "format": ""
        },
        {
            "name": "phoneNumbers",
            "baseName": "phoneNumbers",
            "type": "Array<PhoneNumberStatus>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DetailedTaskStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

