/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class DialogflowConfig {
    /**
    * Enable sentiment analysis from Dialogflow.
    */
    'analyzeSentiment'?: boolean;
    /**
    * Enable partial automated agent reply from Dialogflow.
    */
    'partialAutomatedAgentReply'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analyzeSentiment",
            "baseName": "analyze_sentiment",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "partialAutomatedAgentReply",
            "baseName": "partial_automated_agent_reply",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DialogflowConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

