/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* An enumeration.
*/
export type Exchange = "NONE" | "NASDAQ" | "NYSE" | "AMEX" | "AMX" | "ASX" | "B3" | "BME" | "BSE" | "FRA" | "ICEX" | "JPX" | "JSE" | "KRX" | "LON" | "NSE" | "OMX" | "SEHK" | "SSE" | "STO" | "SWX" | "SZSE" | "TSX" | "TWSE" | "VSE" ;
