/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DownlinkData } from '../models/DownlinkData.ts';
import { UplinkData } from '../models/UplinkData.ts';
import { WirelessCost } from '../models/WirelessCost.ts';
import { WirelessRate } from '../models/WirelessRate.ts';
import { HttpFile } from '../http/http.ts';

export class ExternalWdrDetailRecordDto {
    /**
    * WDR id
    */
    'id'?: string;
    /**
    * Record created time
    */
    'createdAt'?: Date;
    'cost'?: WirelessCost;
    /**
    * Mobile country code.
    */
    'mcc'?: string;
    /**
    * Mobile network code.
    */
    'mnc'?: string;
    'downlinkData'?: DownlinkData;
    /**
    * Session duration in seconds.
    */
    'durationSeconds'?: number;
    /**
    * International mobile subscriber identity
    */
    'imsi'?: string;
    'rate'?: WirelessRate;
    /**
    * Defined sim group name
    */
    'simGroupName'?: string;
    /**
    * Sim group unique identifier
    */
    'simGroupId'?: string;
    /**
    * Sim card unique identifier
    */
    'simCardId'?: string;
    /**
    * Phone number
    */
    'phoneNumber'?: string;
    'uplinkData'?: UplinkData;
    'recordType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "WirelessCost",
            "format": ""
        },
        {
            "name": "mcc",
            "baseName": "mcc",
            "type": "string",
            "format": ""
        },
        {
            "name": "mnc",
            "baseName": "mnc",
            "type": "string",
            "format": ""
        },
        {
            "name": "downlinkData",
            "baseName": "downlink_data",
            "type": "DownlinkData",
            "format": ""
        },
        {
            "name": "durationSeconds",
            "baseName": "duration_seconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "imsi",
            "baseName": "imsi",
            "type": "string",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "WirelessRate",
            "format": ""
        },
        {
            "name": "simGroupName",
            "baseName": "sim_group_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "simGroupId",
            "baseName": "sim_group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "simCardId",
            "baseName": "sim_card_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "uplinkData",
            "baseName": "uplink_data",
            "type": "UplinkData",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalWdrDetailRecordDto.attributeTypeMap;
    }

    public constructor() {
    }
}

