/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ExtVettingProvider {
    'evpId'?: string;
    'displayName'?: string;
    'tcrBillable'?: boolean;
    'vettingClasses'?: Array<string>;
    'vettingInstruction'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "evpId",
            "baseName": "evpId",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "tcrBillable",
            "baseName": "tcrBillable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vettingClasses",
            "baseName": "vettingClasses",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "vettingInstruction",
            "baseName": "vettingInstruction",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExtVettingProvider.attributeTypeMap;
    }

    public constructor() {
    }
}

