/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnchorsiteOverride } from '../models/AnchorsiteOverride.ts';
import { CreateFaxApplicationRequestInbound } from '../models/CreateFaxApplicationRequestInbound.ts';
import { CreateFaxApplicationRequestOutbound } from '../models/CreateFaxApplicationRequestOutbound.ts';
import { HttpFile } from '../http/http.ts';

export class FaxApplication {
    /**
    * Uniquely identifies the resource.
    */
    'id'?: string;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * A user-assigned name to help manage the application.
    */
    'applicationName'?: string;
    /**
    * Specifies whether the connection can be used.
    */
    'active'?: boolean;
    'anchorsiteOverride'?: AnchorsiteOverride;
    /**
    * The URL where webhooks related to this connection will be sent. Must include a scheme, such as \'https\'.
    */
    'webhookEventUrl'?: string;
    /**
    * The failover URL where webhooks related to this connection will be sent if sending to the primary URL fails. Must include a scheme, such as \'https\'.
    */
    'webhookEventFailoverUrl'?: string | null;
    /**
    * Specifies how many seconds to wait before timing out a webhook.
    */
    'webhookTimeoutSecs'?: number | null;
    'inbound'?: CreateFaxApplicationRequestInbound;
    'outbound'?: CreateFaxApplicationRequestOutbound;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: string;
    /**
    * ISO 8601 formatted date indicating when the resource was updated.
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "applicationName",
            "baseName": "application_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "anchorsiteOverride",
            "baseName": "anchorsite_override",
            "type": "AnchorsiteOverride",
            "format": ""
        },
        {
            "name": "webhookEventUrl",
            "baseName": "webhook_event_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookEventFailoverUrl",
            "baseName": "webhook_event_failover_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookTimeoutSecs",
            "baseName": "webhook_timeout_secs",
            "type": "number",
            "format": ""
        },
        {
            "name": "inbound",
            "baseName": "inbound",
            "type": "CreateFaxApplicationRequestInbound",
            "format": ""
        },
        {
            "name": "outbound",
            "baseName": "outbound",
            "type": "CreateFaxApplicationRequestOutbound",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FaxApplication.attributeTypeMap;
    }

    public constructor() {
    }
}



