/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FaxMediaProcessedPayload } from '../models/FaxMediaProcessedPayload.ts';
import { RecordType } from '../models/RecordType.ts';
import { HttpFile } from '../http/http.ts';

export class FaxMediaProcessed {
    'recordType'?: RecordType;
    /**
    * Identifies the resource.
    */
    'id'?: string;
    /**
    * The type of event being delivered.
    */
    'eventType'?: FaxMediaProcessedEventTypeEnum;
    'payload'?: FaxMediaProcessedPayload;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "RecordType",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "FaxMediaProcessedEventTypeEnum",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "FaxMediaProcessedPayload",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FaxMediaProcessed.attributeTypeMap;
    }

    public constructor() {
    }
}


export type FaxMediaProcessedEventTypeEnum = "fax.media.processed" ;

