/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FaxQueuedPayload } from '../models/FaxQueuedPayload.ts';
import { RecordType } from '../models/RecordType.ts';
import { HttpFile } from '../http/http.ts';

export class FaxQueued {
    'recordType'?: RecordType;
    /**
    * Identifies the resource.
    */
    'id'?: string;
    /**
    * The type of event being delivered.
    */
    'eventType'?: FaxQueuedEventTypeEnum;
    'payload'?: FaxQueuedPayload;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "RecordType",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "FaxQueuedEventTypeEnum",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "FaxQueuedPayload",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FaxQueued.attributeTypeMap;
    }

    public constructor() {
    }
}


export type FaxQueuedEventTypeEnum = "fax.queued" ;

