/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* One of UDP, TLS, or TCP. Applies only to connections with IP authentication or FQDN authentication.
*/
export type FqdnConnectionTransportProtocol = "UDP" | "TCP" | "TLS" ;
