/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class GatherUsingSpeakRequest {
    /**
    * The text or SSML to be converted into speech. There is a 3,000 character limit.
    */
    'payload': string;
    /**
    * The text or SSML to be converted into speech when digits don\'t match the `valid_digits` parameter or the number of digits is not between `min` and `max`. There is a 3,000 character limit.
    */
    'invalidPayload'?: string;
    /**
    * The type of the provided payload. The payload can either be plain text, or Speech Synthesis Markup Language (SSML).
    */
    'payloadType'?: GatherUsingSpeakRequestPayloadTypeEnum;
    /**
    * This parameter impacts speech quality, language options and payload types. When using `basic`, only the `en-US` language and payload type `text` are allowed.
    */
    'serviceLevel'?: GatherUsingSpeakRequestServiceLevelEnum;
    /**
    * The gender of the voice used to speak back the text.
    */
    'voice': GatherUsingSpeakRequestVoiceEnum;
    /**
    * The language you want spoken.
    */
    'language': GatherUsingSpeakRequestLanguageEnum;
    /**
    * The minimum number of digits to fetch. This parameter has a minimum value of 1.
    */
    'minimumDigits'?: number;
    /**
    * The maximum number of digits to fetch. This parameter has a maximum value of 128.
    */
    'maximumDigits'?: number;
    /**
    * The maximum number of times that a file should be played back if there is no input from the user on the call.
    */
    'maximumTries'?: number;
    /**
    * The number of milliseconds to wait for a DTMF response after speak ends before a replaying the sound file.
    */
    'timeoutMillis'?: number;
    /**
    * The digit used to terminate input if fewer than `maximum_digits` digits have been gathered.
    */
    'terminatingDigit'?: string;
    /**
    * A list of all digits accepted as valid.
    */
    'validDigits'?: string;
    /**
    * The number of milliseconds to wait for input between digits.
    */
    'interDigitTimeoutMillis'?: number;
    /**
    * Use this field to add state to every subsequent webhook. It must be a valid Base-64 encoded string.
    */
    'clientState'?: string;
    /**
    * Use this field to avoid duplicate commands. Telnyx will ignore any command with the same `command_id` for the same `call_control_id`.
    */
    'commandId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "string",
            "format": ""
        },
        {
            "name": "invalidPayload",
            "baseName": "invalid_payload",
            "type": "string",
            "format": ""
        },
        {
            "name": "payloadType",
            "baseName": "payload_type",
            "type": "GatherUsingSpeakRequestPayloadTypeEnum",
            "format": ""
        },
        {
            "name": "serviceLevel",
            "baseName": "service_level",
            "type": "GatherUsingSpeakRequestServiceLevelEnum",
            "format": ""
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "GatherUsingSpeakRequestVoiceEnum",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "GatherUsingSpeakRequestLanguageEnum",
            "format": ""
        },
        {
            "name": "minimumDigits",
            "baseName": "minimum_digits",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maximumDigits",
            "baseName": "maximum_digits",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maximumTries",
            "baseName": "maximum_tries",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeoutMillis",
            "baseName": "timeout_millis",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "terminatingDigit",
            "baseName": "terminating_digit",
            "type": "string",
            "format": ""
        },
        {
            "name": "validDigits",
            "baseName": "valid_digits",
            "type": "string",
            "format": ""
        },
        {
            "name": "interDigitTimeoutMillis",
            "baseName": "inter_digit_timeout_millis",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "clientState",
            "baseName": "client_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "commandId",
            "baseName": "command_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GatherUsingSpeakRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GatherUsingSpeakRequestPayloadTypeEnum = "text" | "ssml" ;
export type GatherUsingSpeakRequestServiceLevelEnum = "basic" | "premium" ;
export type GatherUsingSpeakRequestVoiceEnum = "male" | "female" ;
export type GatherUsingSpeakRequestLanguageEnum = "arb" | "cmn-CN" | "cy-GB" | "da-DK" | "de-DE" | "en-AU" | "en-GB" | "en-GB-WLS" | "en-IN" | "en-US" | "es-ES" | "es-MX" | "es-US" | "fr-CA" | "fr-FR" | "hi-IN" | "is-IS" | "it-IT" | "ja-JP" | "ko-KR" | "nb-NO" | "nl-NL" | "pl-PL" | "pt-BR" | "pt-PT" | "ro-RO" | "ru-RU" | "sv-SE" | "tr-TR" ;

