/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class GcbPhoneNumber {
    'recordType': GcbPhoneNumberRecordTypeEnum;
    'channelZoneId': string;
    'id'?: string;
    'phoneNumber': string;
    /**
    * ISO 8601 formatted date of when the phone number was created
    */
    'createdAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "GcbPhoneNumberRecordTypeEnum",
            "format": ""
        },
        {
            "name": "channelZoneId",
            "baseName": "channel_zone_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": "+E.164"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcbPhoneNumber.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GcbPhoneNumberRecordTypeEnum = "channel_zone_phone_number" ;

