/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPortingOrder200ResponseMeta } from '../models/GetPortingOrder200ResponseMeta.ts';
import { PortingOrder } from '../models/PortingOrder.ts';
import { HttpFile } from '../http/http.ts';

export class GetPortingOrder200Response {
    'data'?: PortingOrder;
    'meta'?: GetPortingOrder200ResponseMeta;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "PortingOrder",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "GetPortingOrder200ResponseMeta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetPortingOrder200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

