/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaginationMetaSimple } from '../models/PaginationMetaSimple.ts';
import { WebhookDelivery } from '../models/WebhookDelivery.ts';
import { HttpFile } from '../http/http.ts';

export class GetWebhookDeliveries200Response {
    'data'?: Array<WebhookDelivery>;
    'meta'?: PaginationMetaSimple;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<WebhookDelivery>",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PaginationMetaSimple",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetWebhookDeliveries200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

