/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GlobalIpAssignmentUsageMetricGlobalIp } from '../models/GlobalIpAssignmentUsageMetricGlobalIp.ts';
import { GlobalIpAssignmentUsageMetricGlobalIpAssignment } from '../models/GlobalIpAssignmentUsageMetricGlobalIpAssignment.ts';
import { GlobalIpAssignmentUsageMetricReceived } from '../models/GlobalIpAssignmentUsageMetricReceived.ts';
import { GlobalIpAssignmentUsageMetricTransmitted } from '../models/GlobalIpAssignmentUsageMetricTransmitted.ts';
import { HttpFile } from '../http/http.ts';

export class GlobalIpAssignmentUsageMetric {
    /**
    * The timestamp of the metric.
    */
    'timestamp'?: Date;
    'globalIp'?: GlobalIpAssignmentUsageMetricGlobalIp;
    'globalIpAssignment'?: GlobalIpAssignmentUsageMetricGlobalIpAssignment;
    'transmitted'?: GlobalIpAssignmentUsageMetricTransmitted;
    'received'?: GlobalIpAssignmentUsageMetricReceived;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "globalIp",
            "baseName": "global_ip",
            "type": "GlobalIpAssignmentUsageMetricGlobalIp",
            "format": ""
        },
        {
            "name": "globalIpAssignment",
            "baseName": "global_ip_assignment",
            "type": "GlobalIpAssignmentUsageMetricGlobalIpAssignment",
            "format": ""
        },
        {
            "name": "transmitted",
            "baseName": "transmitted",
            "type": "GlobalIpAssignmentUsageMetricTransmitted",
            "format": ""
        },
        {
            "name": "received",
            "baseName": "received",
            "type": "GlobalIpAssignmentUsageMetricReceived",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GlobalIpAssignmentUsageMetric.attributeTypeMap;
    }

    public constructor() {
    }
}

