/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GlobalIpAssignmentHealthMetricGlobalIp } from '../models/GlobalIpAssignmentHealthMetricGlobalIp.ts';
import { GlobalIpAssignmentHealthMetricGlobalIpAssignment } from '../models/GlobalIpAssignmentHealthMetricGlobalIpAssignment.ts';
import { GlobalIpAssignmentHealthMetricHealth } from '../models/GlobalIpAssignmentHealthMetricHealth.ts';
import { HttpFile } from '../http/http.ts';

export class GlobalIpAssignmentHealthMetric {
    /**
    * The timestamp of the metric.
    */
    'timestamp'?: Date;
    'globalIp'?: GlobalIpAssignmentHealthMetricGlobalIp;
    'globalIpAssignment'?: GlobalIpAssignmentHealthMetricGlobalIpAssignment;
    'health'?: GlobalIpAssignmentHealthMetricHealth;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "globalIp",
            "baseName": "global_ip",
            "type": "GlobalIpAssignmentHealthMetricGlobalIp",
            "format": ""
        },
        {
            "name": "globalIpAssignment",
            "baseName": "global_ip_assignment",
            "type": "GlobalIpAssignmentHealthMetricGlobalIpAssignment",
            "format": ""
        },
        {
            "name": "health",
            "baseName": "health",
            "type": "GlobalIpAssignmentHealthMetricHealth",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GlobalIpAssignmentHealthMetric.attributeTypeMap;
    }

    public constructor() {
    }
}

