/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class InitiateCallRequest {
    /**
    * The phone number of the called party. Phone numbers are formatted with a `+` and country code.
    */
    'to': string;
    /**
    * The phone number of the party that initiated the call. Phone numbers are formatted with a `+` and country code.
    */
    '_from': string;
    /**
    * The URL from which Telnyx will retrieve the TeXML call instructions.
    */
    'url'?: string;
    /**
    * HTTP request type used for `Url`. The default value is inherited from TeXML Application setting.
    */
    'urlMethod'?: InitiateCallRequestUrlMethodEnum;
    /**
    * A failover URL for which Telnyx will retrieve the TeXML call instructions if the `Url` is not responding.
    */
    'fallbackUrl'?: string;
    /**
    * URL destination for Telnyx to send status callback events to for the call.
    */
    'statusCallback'?: string;
    /**
    * HTTP request type used for `StatusCallback`.
    */
    'statusCallbackMethod'?: InitiateCallRequestStatusCallbackMethodEnum;
    /**
    * The call events for which Telnyx should send a webhook. Multiple events can be defined when separated by a space.
    */
    'statusCallbackEvent'?: InitiateCallRequestStatusCallbackEventEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "to",
            "baseName": "To",
            "type": "string",
            "format": ""
        },
        {
            "name": "_from",
            "baseName": "From",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "Url",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlMethod",
            "baseName": "UrlMethod",
            "type": "InitiateCallRequestUrlMethodEnum",
            "format": ""
        },
        {
            "name": "fallbackUrl",
            "baseName": "FallbackUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusCallback",
            "baseName": "StatusCallback",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusCallbackMethod",
            "baseName": "StatusCallbackMethod",
            "type": "InitiateCallRequestStatusCallbackMethodEnum",
            "format": ""
        },
        {
            "name": "statusCallbackEvent",
            "baseName": "StatusCallbackEvent",
            "type": "InitiateCallRequestStatusCallbackEventEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InitiateCallRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type InitiateCallRequestUrlMethodEnum = "GET" | "POST" ;
export type InitiateCallRequestStatusCallbackMethodEnum = "GET" | "POST" ;
export type InitiateCallRequestStatusCallbackEventEnum = "initiated" | "ringing" | "answered" | "completed" ;

