/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Language {
    /**
    * The language policy the message should follow
    */
    'policy': LanguagePolicyEnum;
    /**
    * The code of the language or locale to use — Accepts both language and language_locale formats (e.g., en and en_US).
    */
    'code': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "policy",
            "baseName": "policy",
            "type": "LanguagePolicyEnum",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Language.attributeTypeMap;
    }

    public constructor() {
    }
}


export type LanguagePolicyEnum = "fallback" | "deterministic" ;

