/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListObjectsResponseContentsInner } from '../models/ListObjectsResponseContentsInner.ts';
import { HttpFile } from '../http/http.ts';

export class ListObjectsResponse {
    'name'?: string;
    'contents'?: Array<ListObjectsResponseContentsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "contents",
            "baseName": "Contents",
            "type": "Array<ListObjectsResponseContentsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListObjectsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

