/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Metadata } from '../models/Metadata.ts';
import { PortoutDetails } from '../models/PortoutDetails.ts';
import { HttpFile } from '../http/http.ts';

export class ListPortoutRequest200Response {
    'data'?: Array<PortoutDetails>;
    'meta'?: Metadata;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<PortoutDetails>",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "Metadata",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListPortoutRequest200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

