/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ManagedAccountBalance } from '../models/ManagedAccountBalance.ts';
import { HttpFile } from '../http/http.ts';

export class ManagedAccount {
    /**
    * Identifies the type of the resource.
    */
    'recordType': ManagedAccountRecordTypeEnum;
    /**
    * Uniquely identifies the managed account.
    */
    'id': string;
    /**
    * The managed account\'s email.
    */
    'email': string;
    /**
    * The managed account\'s V2 API access key
    */
    'apiKey': string;
    /**
    * The manager account\'s email, which serves as the V1 API user identifier
    */
    'apiUser': string;
    /**
    * The managed account\'s V1 API token
    */
    'apiToken': string;
    /**
    * The organization the managed account is associated with.
    */
    'organizationName'?: string;
    /**
    * The ID of the manager account associated with the managed account.
    */
    'managerAccountId': string;
    'balance'?: ManagedAccountBalance;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt': string;
    /**
    * ISO 8601 formatted date indicating when the resource was updated.
    */
    'updatedAt': string;
    /**
    * Boolean value that indicates if the managed account is able to have custom pricing set for it or not. If false, uses the pricing of the manager account. Defaults to false. There may be time lag between when the value is changed and pricing changes take effect.
    */
    'managedAccountAllowCustomPricing'?: boolean;
    /**
    * Boolean value that indicates if the billing information and charges to the managed account \"roll up\" to the manager account. If true, the managed account will not have its own balance and will use the shared balance with the manager account. This value cannot be changed after account creation without going through Telnyx support as changes require manual updates to the account ledger. Defaults to false.
    */
    'rollupBilling'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "ManagedAccountRecordTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "UUID"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "apiKey",
            "baseName": "api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiUser",
            "baseName": "api_user",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiToken",
            "baseName": "api_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationName",
            "baseName": "organization_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "managerAccountId",
            "baseName": "manager_account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "ManagedAccountBalance",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "managedAccountAllowCustomPricing",
            "baseName": "managed_account_allow_custom_pricing",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rollupBilling",
            "baseName": "rollup_billing",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ManagedAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ManagedAccountRecordTypeEnum = "managed_account" ;

