/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MdrUsageRecord } from '../models/MdrUsageRecord.ts';
import { HttpFile } from '../http/http.ts';

export class MdrUsageReportResponse {
    /**
    * Identifies the resource
    */
    'id'?: string;
    'startDate'?: Date;
    'endDate'?: Date;
    'connections'?: Array<number>;
    'aggregationType'?: MdrUsageReportResponseAggregationTypeEnum;
    'status'?: MdrUsageReportResponseStatusEnum;
    'reportUrl'?: string;
    'result'?: Array<MdrUsageRecord>;
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'profiles'?: string;
    'recordType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "connections",
            "baseName": "connections",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "aggregationType",
            "baseName": "aggregation_type",
            "type": "MdrUsageReportResponseAggregationTypeEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MdrUsageReportResponseStatusEnum",
            "format": ""
        },
        {
            "name": "reportUrl",
            "baseName": "report_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<MdrUsageRecord>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdrUsageReportResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type MdrUsageReportResponseAggregationTypeEnum = "NO_AGGREGATION" | "PROFILE" | "TAGS" ;
export type MdrUsageReportResponseStatusEnum = "PENDING" | "COMPLETE" | "FAILED" | "EXPIRED" ;

