/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class MediaResource {
    /**
    * Uniquely identifies a media resource.
    */
    'mediaName'?: string;
    /**
    * ISO 8601 formatted date of when the media resource will expire and be deleted.
    */
    'expiresAt'?: string;
    /**
    * ISO 8601 formatted date of when the media resource was created
    */
    'createdAt'?: string;
    /**
    * ISO 8601 formatted date of when the media resource was last updated
    */
    'updatedAt'?: string;
    /**
    * Content type of the file
    */
    'contentType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mediaName",
            "baseName": "media_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MediaResource.attributeTypeMap;
    }

    public constructor() {
    }
}

