/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HostedNumber } from '../models/HostedNumber.ts';
import { HttpFile } from '../http/http.ts';

export class MessagingHostedNumberOrder {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * Resource unique identifier.
    */
    'id'?: string;
    /**
    * Automatically associate the number with this messaging profile ID when the order is complete.
    */
    'messagingProfileId'?: string | null;
    'status'?: MessagingHostedNumberOrderStatusEnum;
    'phoneNumbers'?: Array<HostedNumber>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "messagingProfileId",
            "baseName": "messaging_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MessagingHostedNumberOrderStatusEnum",
            "format": ""
        },
        {
            "name": "phoneNumbers",
            "baseName": "phone_numbers",
            "type": "Array<HostedNumber>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MessagingHostedNumberOrder.attributeTypeMap;
    }

    public constructor() {
    }
}


export type MessagingHostedNumberOrderStatusEnum = "failed" | "pending" | "successful" ;

