/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NumberPoolSettings } from '../models/NumberPoolSettings.ts';
import { UrlShortenerSettings } from '../models/UrlShortenerSettings.ts';
import { HttpFile } from '../http/http.ts';

export class MessagingProfile {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: MessagingProfileRecordTypeEnum;
    /**
    * Identifies the type of resource.
    */
    'id'?: string;
    /**
    * A user friendly name for the messaging profile.
    */
    'name'?: string;
    /**
    * Specifies whether the messaging profile is enabled or not.
    */
    'enabled'?: boolean;
    /**
    * The URL where webhooks related to this messaging profile will be sent.
    */
    'webhookUrl'?: string | null;
    /**
    * The failover URL where webhooks related to this messaging profile will be sent if sending to the primary URL fails.
    */
    'webhookFailoverUrl'?: string | null;
    /**
    * Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 2010-04-01 format.
    */
    'webhookApiVersion'?: MessagingProfileWebhookApiVersionEnum;
    /**
    * Destinations to which the messaging profile is allowed to send. If set to `null`, all destinations will be allowed. Setting a value of `[\"*\"]` has the equivalent effect. The elements in the list must be valid ISO 3166-1 alpha-2 country codes.
    */
    'whitelistedDestinations'?: Array<string> | null;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: Date;
    /**
    * ISO 8601 formatted date indicating when the resource was updated.
    */
    'updatedAt'?: Date;
    /**
    * Secret used to authenticate with v1 endpoints.
    */
    'v1Secret'?: string;
    'numberPoolSettings'?: NumberPoolSettings | null;
    'urlShortenerSettings'?: UrlShortenerSettings | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "MessagingProfileRecordTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookFailoverUrl",
            "baseName": "webhook_failover_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookApiVersion",
            "baseName": "webhook_api_version",
            "type": "MessagingProfileWebhookApiVersionEnum",
            "format": ""
        },
        {
            "name": "whitelistedDestinations",
            "baseName": "whitelisted_destinations",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "v1Secret",
            "baseName": "v1_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "numberPoolSettings",
            "baseName": "number_pool_settings",
            "type": "NumberPoolSettings",
            "format": ""
        },
        {
            "name": "urlShortenerSettings",
            "baseName": "url_shortener_settings",
            "type": "UrlShortenerSettings",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MessagingProfile.attributeTypeMap;
    }

    public constructor() {
    }
}


export type MessagingProfileRecordTypeEnum = "messaging_profile" ;
export type MessagingProfileWebhookApiVersionEnum = "1" | "2" | "2010-04-01" ;

