/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Mno {
    /**
    * Unique network identifier assigned to MNO.
    */
    'networkId': number;
    /**
    * Display name of the mobile network operator.
    */
    'displayName': string;
    /**
    * NetNumber OSR \'campaign_id\' property\'s \'status\' attribute holds individual MNO campaign operation status. The \'status\' attribute leverages bitmasking technique to store multiple MNOs\' operating status. The campaign operation status is reduced to \'1\' or \'0\' value where \'1\' indicate an \'ACTIVE\' status and \'0\' represents every other non-active statuses, including REVIEW, REJECT and SUSPEND. The \'osrBitmaskIndex\' holds the bitmask index of the MNO. For example, T-Mobile\'s bitmask index is 2, which implies T-Mobile\'s campaign operation status is stored in bit #2, or 3rd bit when counting from right.
    */
    'osrBitmaskIndex': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkId",
            "baseName": "networkId",
            "type": "number",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "osrBitmaskIndex",
            "baseName": "osrBitmaskIndex",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Mno.attributeTypeMap;
    }

    public constructor() {
    }
}

