/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* A Notification Channel
*/
export class NotificationChannel {
    /**
    * A UUID.
    */
    'id'?: string;
    /**
    * A UUID reference to the associated Notification Profile.
    */
    'notificationProfileId'?: string;
    /**
    * A Channel Type ID
    */
    'channelTypeId'?: NotificationChannelChannelTypeIdEnum;
    /**
    * The destination associated with the channel type.
    */
    'channelDestination'?: string;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: Date;
    /**
    * ISO 8601 formatted date indicating when the resource was updated.
    */
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "notificationProfileId",
            "baseName": "notification_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelTypeId",
            "baseName": "channel_type_id",
            "type": "NotificationChannelChannelTypeIdEnum",
            "format": ""
        },
        {
            "name": "channelDestination",
            "baseName": "channel_destination",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return NotificationChannel.attributeTypeMap;
    }

    public constructor() {
    }
}


export type NotificationChannelChannelTypeIdEnum = "sms" | "voice" | "email" | "webhook" ;

