/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class OutboundMessagePayloadFrom {
    /**
    * Sending address (+E.164 formatted phone number, alphanumeric sender ID, or short code).
    */
    'phoneNumber'?: string;
    /**
    * The carrier of the receiver.
    */
    'carrier'?: string;
    /**
    * The line-type of the receiver.
    */
    'lineType'?: OutboundMessagePayloadFromLineTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": "address"
        },
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string",
            "format": ""
        },
        {
            "name": "lineType",
            "baseName": "line_type",
            "type": "OutboundMessagePayloadFromLineTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OutboundMessagePayloadFrom.attributeTypeMap;
    }

    public constructor() {
    }
}


export type OutboundMessagePayloadFromLineTypeEnum = "Wireline" | "Wireless" | "VoWiFi" | "VoIP" | "Pre-Paid Wireless" | "" ;

