/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class OutboundMessagePayloadMediaInner {
    /**
    * The url of the media requested to be sent.
    */
    'url'?: string;
    /**
    * The MIME type of the requested media.
    */
    'contentType'?: string | null;
    /**
    * The SHA256 hash of the requested media.
    */
    'sha256'?: string | null;
    /**
    * The size of the requested media.
    */
    'size'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string",
            "format": "mime-type"
        },
        {
            "name": "sha256",
            "baseName": "sha256",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OutboundMessagePayloadMediaInner.attributeTypeMap;
    }

    public constructor() {
    }
}

