/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class OutboundCallRecording {
    /**
    * Specifies which calls are recorded.
    */
    'callRecordingType'?: OutboundCallRecordingCallRecordingTypeEnum;
    /**
    * When call_recording_type is \'by_caller_phone_number\', only outbound calls using one of these numbers will be recorded. Numbers must be specified in E164 format.
    */
    'callRecordingCallerPhoneNumbers'?: Array<string>;
    /**
    * When using \'dual\' channels, the final audio file will be a stereo recording with the first leg on channel A, and the rest on channel B.
    */
    'callRecordingChannels'?: OutboundCallRecordingCallRecordingChannelsEnum;
    /**
    * The audio file format for calls being recorded.
    */
    'callRecordingFormat'?: OutboundCallRecordingCallRecordingFormatEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "callRecordingType",
            "baseName": "call_recording_type",
            "type": "OutboundCallRecordingCallRecordingTypeEnum",
            "format": ""
        },
        {
            "name": "callRecordingCallerPhoneNumbers",
            "baseName": "call_recording_caller_phone_numbers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "callRecordingChannels",
            "baseName": "call_recording_channels",
            "type": "OutboundCallRecordingCallRecordingChannelsEnum",
            "format": ""
        },
        {
            "name": "callRecordingFormat",
            "baseName": "call_recording_format",
            "type": "OutboundCallRecordingCallRecordingFormatEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OutboundCallRecording.attributeTypeMap;
    }

    public constructor() {
    }
}


export type OutboundCallRecordingCallRecordingTypeEnum = "all" | "none" | "by_caller_phone_number" ;
export type OutboundCallRecordingCallRecordingChannelsEnum = "single" | "dual" ;
export type OutboundCallRecordingCallRecordingFormatEnum = "wav" | "mp3" ;

