/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class PatchRoomRequest {
    /**
    * The unique (within the Telnyx account scope) name of the room.
    */
    'uniqueName'?: string;
    /**
    * The maximum amount of participants allowed in a room. If new participants try to join after that limit is reached, their request will be rejected.
    */
    'maxParticipants'?: number;
    /**
    * Enable or disable recording for that room.
    */
    'enableRecording'?: boolean;
    /**
    * The URL where webhooks related to this room will be sent. Must include a scheme, such as \'https\'.
    */
    'webhookEventUrl'?: string;
    /**
    * The failover URL where webhooks related to this room will be sent if sending to the primary URL fails. Must include a scheme, such as \'https\'.
    */
    'webhookEventFailoverUrl'?: string | null;
    /**
    * Specifies how many seconds to wait before timing out a webhook.
    */
    'webhookTimeoutSecs'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uniqueName",
            "baseName": "unique_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxParticipants",
            "baseName": "max_participants",
            "type": "number",
            "format": ""
        },
        {
            "name": "enableRecording",
            "baseName": "enable_recording",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webhookEventUrl",
            "baseName": "webhook_event_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookEventFailoverUrl",
            "baseName": "webhook_event_failover_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "webhookTimeoutSecs",
            "baseName": "webhook_timeout_secs",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatchRoomRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

