/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class PhoneNumberDetailed {
    /**
    * Uniquely identifies the resource.
    */
    'id'?: string;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * The +E.164-formatted phone number associated with this record.
    */
    'phoneNumber'?: string;
    /**
    * The phone number\'s current status.
    */
    'status'?: PhoneNumberDetailedStatusEnum;
    /**
    * A list of user-assigned tags to help manage the phone number.
    */
    'tags'?: Array<string>;
    /**
    * If someone attempts to port your phone number away from Telnyx and your phone number has an external PIN set, Telnyx will attempt to verify that you provided the correct external PIN to the winning carrier. Note that not all carriers cooperate with this security mechanism.
    */
    'externalPin'?: string;
    /**
    * The user-assigned name of the connection to be associated with this phone number.
    */
    'connectionName'?: string;
    /**
    * Identifies the connection associated with the phone number.
    */
    'connectionId'?: string;
    /**
    * A customer reference string for customer look ups.
    */
    'customerReference'?: string;
    /**
    * Identifies the messaging profile associated with the phone number.
    */
    'messagingProfileId'?: string;
    /**
    * The name of the messaging profile associated with the phone number.
    */
    'messagingProfileName'?: string;
    /**
    * Identifies the billing group associated with the phone number.
    */
    'billingGroupId'?: string;
    /**
    * Indicates whether emergency services are enabled for this number.
    */
    'emergencyEnabled'?: boolean;
    /**
    * Identifies the emergency address associated with the phone number.
    */
    'emergencyAddressId'?: string;
    /**
    * Indicates if call forwarding will be enabled for this number if forwards_to and forwarding_type are filled in. Defaults to true for backwards compatibility with APIV1 use of numbers endpoints.
    */
    'callForwardingEnabled'?: boolean;
    /**
    * Indicates whether a CNAM listing is enabled for this number.
    */
    'cnamListingEnabled'?: boolean;
    /**
    * Indicates whether caller ID is enabled for this number.
    */
    'callerIdNameEnabled'?: boolean;
    /**
    * Indicates whether call recording is enabled for this number.
    */
    'callRecordingEnabled'?: boolean;
    /**
    * Indicates whether T38 Fax Gateway for inbound calls to this number.
    */
    't38FaxGatewayEnabled'?: boolean;
    /**
    * ISO 8601 formatted date indicating when the resource was purchased.
    */
    'purchasedAt'?: string;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: string;
    /**
    * Specifies whether the number can have overrides to the routing settings on itself (enabled) or if it uses the associated connection for all routing settings (disabled). Defaults to disabled or the value set on your user profile in default_number_routing_setting. There are performance advantages to using disabled and setting all routing information at the connection level.
    */
    'numberLevelRouting'?: PhoneNumberDetailedNumberLevelRoutingEnum;
    /**
    * The phone number\'s type.
    */
    'phoneNumberType'?: PhoneNumberDetailedPhoneNumberTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PhoneNumberDetailedStatusEnum",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "externalPin",
            "baseName": "external_pin",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionName",
            "baseName": "connection_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerReference",
            "baseName": "customer_reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "messagingProfileId",
            "baseName": "messaging_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messagingProfileName",
            "baseName": "messaging_profile_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingGroupId",
            "baseName": "billing_group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "emergencyEnabled",
            "baseName": "emergency_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emergencyAddressId",
            "baseName": "emergency_address_id",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "callForwardingEnabled",
            "baseName": "call_forwarding_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cnamListingEnabled",
            "baseName": "cnam_listing_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "callerIdNameEnabled",
            "baseName": "caller_id_name_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "callRecordingEnabled",
            "baseName": "call_recording_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "t38FaxGatewayEnabled",
            "baseName": "t38_fax_gateway_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "purchasedAt",
            "baseName": "purchased_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "numberLevelRouting",
            "baseName": "number_level_routing",
            "type": "PhoneNumberDetailedNumberLevelRoutingEnum",
            "format": ""
        },
        {
            "name": "phoneNumberType",
            "baseName": "phone_number_type",
            "type": "PhoneNumberDetailedPhoneNumberTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PhoneNumberDetailed.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PhoneNumberDetailedStatusEnum = "purchase-pending" | "purchase-failed" | "port-pending" | "port-failed" | "active" | "deleted" | "emergency-only" | "ported-out" | "port-out-pending" ;
export type PhoneNumberDetailedNumberLevelRoutingEnum = "enabled" | "disabled" ;
export type PhoneNumberDetailedPhoneNumberTypeEnum = "local" | "toll_free" | "mobile" | "national" | "shared_cost" | "landline" ;

