/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PhoneNumberCampaign } from '../models/PhoneNumberCampaign.ts';
import { HttpFile } from '../http/http.ts';

export class PhoneNumberCampaignPaginated {
    'records': Array<PhoneNumberCampaign>;
    'page': number;
    'totalRecords': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "records",
            "baseName": "records",
            "type": "Array<PhoneNumberCampaign>",
            "format": ""
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalRecords",
            "baseName": "totalRecords",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PhoneNumberCampaignPaginated.attributeTypeMap;
    }

    public constructor() {
    }
}

