/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PortingOrderActivationSettings } from '../models/PortingOrderActivationSettings.ts';
import { PortingOrderDocuments } from '../models/PortingOrderDocuments.ts';
import { PortingOrderEndUser } from '../models/PortingOrderEndUser.ts';
import { PortingOrderMisc } from '../models/PortingOrderMisc.ts';
import { PortingOrderPhoneNumberConfiguration } from '../models/PortingOrderPhoneNumberConfiguration.ts';
import { PortingOrderRequirement } from '../models/PortingOrderRequirement.ts';
import { PortingOrderStatus } from '../models/PortingOrderStatus.ts';
import { PortingOrderUserFeedback } from '../models/PortingOrderUserFeedback.ts';
import { HttpFile } from '../http/http.ts';

export class PortingOrder {
    /**
    * Uniquely identifies this porting order
    */
    'id'?: string;
    /**
    * A customer-specified reference number for customer bookkeeping purposes
    */
    'customerReference'?: string;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: Date;
    /**
    * ISO 8601 formatted date indicating when the resource was created.
    */
    'updatedAt'?: Date;
    'status'?: PortingOrderStatus;
    /**
    * A key to reference this porting order when contacting Telnyx customer support. This information is not available in draft porting orders.
    */
    'supportKey'?: string;
    /**
    * A key to reference for the porting order group when contacting Telnyx customer support. This information is not available for porting orders in `draft` state
    */
    'parentSupportKey'?: string;
    /**
    * Count of phone numbers associated with this porting order
    */
    'portingPhoneNumbersCount'?: number;
    /**
    * Identifies the old service provider
    */
    'oldServiceProviderOcn'?: string;
    'documents'?: PortingOrderDocuments;
    'misc'?: PortingOrderMisc;
    'endUser'?: PortingOrderEndUser;
    'activationSettings'?: PortingOrderActivationSettings;
    'phoneNumberConfiguration'?: PortingOrderPhoneNumberConfiguration;
    /**
    * The type of the phone number
    */
    'phoneNumberType'?: PortingOrderPhoneNumberTypeEnum;
    /**
    * A description of the porting order
    */
    'description'?: string;
    /**
    * List of documentation requirements for porting numbers.
    */
    'requirements'?: Array<PortingOrderRequirement>;
    /**
    * Is true when the required documentation is met
    */
    'requirementsMet'?: boolean;
    'userFeedback'?: PortingOrderUserFeedback;
    /**
    * Identifies the user (or organization) who requested the porting order
    */
    'userId'?: string;
    'webhookUrl'?: string;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "customerReference",
            "baseName": "customer_reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PortingOrderStatus",
            "format": ""
        },
        {
            "name": "supportKey",
            "baseName": "support_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentSupportKey",
            "baseName": "parent_support_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "portingPhoneNumbersCount",
            "baseName": "porting_phone_numbers_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "oldServiceProviderOcn",
            "baseName": "old_service_provider_ocn",
            "type": "string",
            "format": ""
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "PortingOrderDocuments",
            "format": ""
        },
        {
            "name": "misc",
            "baseName": "misc",
            "type": "PortingOrderMisc",
            "format": ""
        },
        {
            "name": "endUser",
            "baseName": "end_user",
            "type": "PortingOrderEndUser",
            "format": ""
        },
        {
            "name": "activationSettings",
            "baseName": "activation_settings",
            "type": "PortingOrderActivationSettings",
            "format": ""
        },
        {
            "name": "phoneNumberConfiguration",
            "baseName": "phone_number_configuration",
            "type": "PortingOrderPhoneNumberConfiguration",
            "format": ""
        },
        {
            "name": "phoneNumberType",
            "baseName": "phone_number_type",
            "type": "PortingOrderPhoneNumberTypeEnum",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "requirements",
            "baseName": "requirements",
            "type": "Array<PortingOrderRequirement>",
            "format": ""
        },
        {
            "name": "requirementsMet",
            "baseName": "requirements_met",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userFeedback",
            "baseName": "user_feedback",
            "type": "PortingOrderUserFeedback",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortingOrder.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PortingOrderPhoneNumberTypeEnum = "landline" | "local" | "mobile" | "national" | "shared_cost" | "toll_free" ;

