/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PortabilityStatus } from '../models/PortabilityStatus.ts';
import { PortingOrderActivationStatus } from '../models/PortingOrderActivationStatus.ts';
import { HttpFile } from '../http/http.ts';

export class PortingPhoneNumber {
    /**
    * The current status of the porting order
    */
    'portingOrderStatus'?: PortingPhoneNumberPortingOrderStatusEnum;
    /**
    * The type of the phone number
    */
    'phoneNumberType'?: PortingPhoneNumberPhoneNumberTypeEnum;
    /**
    * E164 formatted phone number
    */
    'phoneNumber'?: string;
    /**
    * Identifies the associated port request
    */
    'portingOrderId'?: string;
    /**
    * A key to reference this porting order when contacting Telnyx customer support
    */
    'supportKey'?: string;
    'activationStatus'?: PortingOrderActivationStatus;
    'portabilityStatus'?: PortabilityStatus;
    /**
    * The current status of the requirements in a INTL porting order
    */
    'requirementsStatus'?: PortingPhoneNumberRequirementsStatusEnum;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "portingOrderStatus",
            "baseName": "porting_order_status",
            "type": "PortingPhoneNumberPortingOrderStatusEnum",
            "format": ""
        },
        {
            "name": "phoneNumberType",
            "baseName": "phone_number_type",
            "type": "PortingPhoneNumberPhoneNumberTypeEnum",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "portingOrderId",
            "baseName": "porting_order_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "supportKey",
            "baseName": "support_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "activationStatus",
            "baseName": "activation_status",
            "type": "PortingOrderActivationStatus",
            "format": ""
        },
        {
            "name": "portabilityStatus",
            "baseName": "portability_status",
            "type": "PortabilityStatus",
            "format": ""
        },
        {
            "name": "requirementsStatus",
            "baseName": "requirements_status",
            "type": "PortingPhoneNumberRequirementsStatusEnum",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortingPhoneNumber.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PortingPhoneNumberPortingOrderStatusEnum = "draft" | "in-process" | "submitted" | "exception" | "foc-date-confirmed" | "cancel-pending" | "ported" | "cancelled" ;
export type PortingPhoneNumberPhoneNumberTypeEnum = "landline" | "local" | "mobile" | "national" | "shared_cost" | "toll_free" ;
export type PortingPhoneNumberRequirementsStatusEnum = "requirement-info-pending" | "requirement-info-under-review" | "requirement-info-exception" | "approved" ;

