/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class PortingOrderEndUserAdmin {
    /**
    * Person Name or Company name requesting the port
    */
    'entityName'?: string;
    /**
    * Name of person authorizing the porting order
    */
    'authPersonName'?: string;
    /**
    * Billing phone number associated with these phone numbers
    */
    'billingPhoneNumber'?: string;
    /**
    * The authorized person\'s account number with the current service provider
    */
    'accountNumber'?: string;
    /**
    * European tax identification number. Applicable only in the European Union
    */
    'taxIdentifier'?: string;
    /**
    * PIN/passcode possibly required by the old service provider for extra verification
    */
    'pinPasscode'?: string;
    /**
    * European business identification number. Applicable only in the European Union
    */
    'businessIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entityName",
            "baseName": "entity_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "authPersonName",
            "baseName": "auth_person_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingPhoneNumber",
            "baseName": "billing_phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxIdentifier",
            "baseName": "tax_identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "pinPasscode",
            "baseName": "pin_passcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessIdentifier",
            "baseName": "business_identifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortingOrderEndUserAdmin.attributeTypeMap;
    }

    public constructor() {
    }
}

