/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class PortingOrderDocuments {
    /**
    * Returned ID of the submitted LOA via the Documents endpoint
    */
    'loa'?: string;
    /**
    * Returned ID of the submitted Invoice via the Documents endpoint
    */
    'invoice'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "loa",
            "baseName": "loa",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return PortingOrderDocuments.attributeTypeMap;
    }

    public constructor() {
    }
}

