/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PortingOrderActivationStatus } from '../models/PortingOrderActivationStatus.ts';
import { HttpFile } from '../http/http.ts';

export class PortingOrderActivationSettings {
    /**
    * ISO 8601 formatted Date/Time requested for the FOC date
    */
    'focDatetimeRequested'?: Date;
    /**
    * ISO 8601 formatted Date/Time of the FOC date
    */
    'focDatetimeActual'?: Date;
    /**
    * Indicates whether this porting order is eligible for FastPort
    */
    'fastPortEligible'?: boolean;
    'activationStatus'?: PortingOrderActivationStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "focDatetimeRequested",
            "baseName": "foc_datetime_requested",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "focDatetimeActual",
            "baseName": "foc_datetime_actual",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fastPortEligible",
            "baseName": "fast_port_eligible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "activationStatus",
            "baseName": "activation_status",
            "type": "PortingOrderActivationStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PortingOrderActivationSettings.attributeTypeMap;
    }

    public constructor() {
    }
}



