/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class PostPortRequestSupportingDocumentsRequestDocumentsInner {
    /**
    * Identifies the type of the document
    */
    'type': PostPortRequestSupportingDocumentsRequestDocumentsInnerTypeEnum;
    /**
    * Identifies the associated document
    */
    'documentId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PostPortRequestSupportingDocumentsRequestDocumentsInnerTypeEnum",
            "format": ""
        },
        {
            "name": "documentId",
            "baseName": "document_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return PostPortRequestSupportingDocumentsRequestDocumentsInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PostPortRequestSupportingDocumentsRequestDocumentsInnerTypeEnum = "loa" | "invoice" ;

