/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Exchange } from '../models/Exchange.ts';
import { HttpFile } from '../http/http.ts';

export class PublicCompany {
    'symbol'?: string;
    'exchange'?: Exchange;
    'iso2'?: string;
    'isin'?: string;
    'displayName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "exchange",
            "baseName": "exchange",
            "type": "Exchange",
            "format": ""
        },
        {
            "name": "iso2",
            "baseName": "iso2",
            "type": "string",
            "format": ""
        },
        {
            "name": "isin",
            "baseName": "isin",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicCompany.attributeTypeMap;
    }

    public constructor() {
    }
}



