/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* The summary of the resource that have been assigned to the Private Wireless Gateway
*/
export class PWGAssignedResourcesSummary {
    /**
    * The type of the resource assigned to the Private Wireless Gateway
    */
    'recordType'?: string;
    /**
    * The current count of a resource type assigned to the Private Wireless Gateway
    */
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PWGAssignedResourcesSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

