/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class RegionInformation {
    'regionType'?: RegionInformationRegionTypeEnum;
    'regionName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "regionType",
            "baseName": "region_type",
            "type": "RegionInformationRegionTypeEnum",
            "format": ""
        },
        {
            "name": "regionName",
            "baseName": "region_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RegionInformation.attributeTypeMap;
    }

    public constructor() {
    }
}


export type RegionInformationRegionTypeEnum = "country_code" | "rate_center" | "state" | "location" ;

