/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ReplacedLinkClick {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * The original link that was sent in the message.
    */
    'url'?: string;
    /**
    * Sending address (+E.164 formatted phone number, alphanumeric sender ID, or short code).
    */
    'to'?: string;
    /**
    * The message ID associated with the clicked link.
    */
    'messageId'?: string;
    /**
    * ISO 8601 formatted date indicating when the message request was received.
    */
    'timeClicked'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": "address"
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "timeClicked",
            "baseName": "time_clicked",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ReplacedLinkClick.attributeTypeMap;
    }

    public constructor() {
    }
}

