/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssignProfileToCampaignResponse } from '../models/AssignProfileToCampaignResponse.ts';
import { SettingsDataErrorMessage } from '../models/SettingsDataErrorMessage.ts';
import { HttpFile } from '../http/http.ts';

export class ResponseAssignMessagingProfileToCampaignPublicPhonenumberassignmentbyprofilePost {
    /**
    * The ID of the messaging profile that you want to link to the specified campaign.
    */
    'messagingProfileId': string;
    /**
    * The TCR ID of the shared campaign you want to link to the specified messaging profile (for campaigns not created using Telnyx 10DLC services only). If you supply this ID in the request, do not also include a campaignId.
    */
    'tcrCampaignId'?: string;
    /**
    * The ID of the campaign you want to link to the specified messaging profile. If you supply this ID in the request, do not also include a tcrCampaignId.
    */
    'campaignId'?: string;
    /**
    * The ID of the task associated with assigning a messaging profile to a campaign.
    */
    'taskId': string;
    'message': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messagingProfileId",
            "baseName": "messagingProfileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "tcrCampaignId",
            "baseName": "tcrCampaignId",
            "type": "string",
            "format": ""
        },
        {
            "name": "campaignId",
            "baseName": "campaignId",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponseAssignMessagingProfileToCampaignPublicPhonenumberassignmentbyprofilePost.attributeTypeMap;
    }

    public constructor() {
    }
}

