/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SessionEndedPayload } from '../models/SessionEndedPayload.ts';
import { HttpFile } from '../http/http.ts';

export class SessionEnded {
    /**
    * An identifier for the type of the resource.
    */
    'recordType'?: SessionEndedRecordTypeEnum;
    /**
    * The type of event being delivered.
    */
    'eventType'?: SessionEndedEventTypeEnum;
    /**
    * Uniquely identify the event.
    */
    'id'?: string;
    /**
    * ISO 8601 datetime of when the event occurred.
    */
    'occurredAt'?: Date;
    'payload'?: SessionEndedPayload;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "SessionEndedRecordTypeEnum",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "SessionEndedEventTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "occurredAt",
            "baseName": "occurred_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "SessionEndedPayload",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SessionEnded.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SessionEndedRecordTypeEnum = "event" ;
export type SessionEndedEventTypeEnum = "video.room.session.ended" ;

