/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsumedData } from '../models/ConsumedData.ts';
import { SIMCardGroupDataLimit } from '../models/SIMCardGroupDataLimit.ts';
import { HttpFile } from '../http/http.ts';

export class SIMCardGroup {
    /**
    * Identifies the resource.
    */
    'id'?: string;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * Indicates whether the SIM card group is the users default group.<br/>The default group is created for the user and can not be removed.
    */
    '_default'?: boolean;
    /**
    * A user friendly name for the SIM card group.
    */
    'name'?: string;
    'dataLimit'?: SIMCardGroupDataLimit;
    'consumedData'?: ConsumedData;
    /**
    * The identification of the related Private Wireless Gateway resource.
    */
    'privateWirelessGatewayId'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the resource was created.
    */
    'createdAt'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the resource was updated.
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataLimit",
            "baseName": "data_limit",
            "type": "SIMCardGroupDataLimit",
            "format": ""
        },
        {
            "name": "consumedData",
            "baseName": "consumed_data",
            "type": "ConsumedData",
            "format": ""
        },
        {
            "name": "privateWirelessGatewayId",
            "baseName": "private_wireless_gateway_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SIMCardGroup.attributeTypeMap;
    }

    public constructor() {
    }
}

