/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MobileOperatorNetworkPreferencesRequest } from '../models/MobileOperatorNetworkPreferencesRequest.ts';
import { HttpFile } from '../http/http.ts';

export class SIMCardNetworkPreferencesPutRequest {
    /**
    * A list of mobile operator networks and the priority that should be applied when the SIM is connecting to the network.
    */
    'mobileOperatorNetworksPreferences'?: Array<MobileOperatorNetworkPreferencesRequest>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mobileOperatorNetworksPreferences",
            "baseName": "mobile_operator_networks_preferences",
            "type": "Array<MobileOperatorNetworkPreferencesRequest>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SIMCardNetworkPreferencesPutRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

