/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* This object represents an Over the Air (OTA) update request. It allows tracking the current status of a operation that apply settings in a particular SIM card. <br/><br/>
*/
export class SimplifiedOTAUpdate {
    /**
    * Identifies the resource.
    */
    'id'?: string;
    'recordType'?: string;
    /**
    * The identification UUID of the related SIM card resource.
    */
    'simCardId'?: string;
    /**
    * Represents the type of the operation requested. This will relate directly to the source of the request.
    */
    'type'?: SimplifiedOTAUpdateTypeEnum;
    'status'?: SimplifiedOTAUpdateStatusEnum;
    /**
    * ISO 8601 formatted date-time indicating when the resource was created.
    */
    'createdAt'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the resource was updated.
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "simCardId",
            "baseName": "sim_card_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SimplifiedOTAUpdateTypeEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SimplifiedOTAUpdateStatusEnum",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimplifiedOTAUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SimplifiedOTAUpdateTypeEnum = "sim_card_network_preferences" ;
export type SimplifiedOTAUpdateStatusEnum = "in-progress" | "completed" | "failed" ;

