/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DialogflowConfig } from '../models/DialogflowConfig.ts';
import { HttpFile } from '../http/http.ts';

export class StartStreamingRequest {
    /**
    * The destination WebSocket address where the stream is going to be delivered.
    */
    'streamUrl'?: string;
    /**
    * Specifies which track should be streamed.
    */
    'streamTrack'?: StartStreamingRequestStreamTrackEnum;
    /**
    * Enables Dialogflow for the current call. The default value is false.
    */
    'enableDialogflow'?: boolean;
    'dialogflowConfig'?: DialogflowConfig;
    /**
    * Use this field to add state to every subsequent webhook. It must be a valid Base-64 encoded string.
    */
    'clientState'?: string;
    /**
    * Use this field to avoid duplicate commands. Telnyx will ignore any command with the same `command_id` for the same `call_control_id`.
    */
    'commandId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "streamUrl",
            "baseName": "stream_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "streamTrack",
            "baseName": "stream_track",
            "type": "StartStreamingRequestStreamTrackEnum",
            "format": ""
        },
        {
            "name": "enableDialogflow",
            "baseName": "enable_dialogflow",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dialogflowConfig",
            "baseName": "dialogflow_config",
            "type": "DialogflowConfig",
            "format": ""
        },
        {
            "name": "clientState",
            "baseName": "client_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "commandId",
            "baseName": "command_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StartStreamingRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type StartStreamingRequestStreamTrackEnum = "inbound_track" | "outbound_track" | "both_tracks" ;

