/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class TelephonyCredential {
    /**
    * Identifies the resource.
    */
    'id'?: string;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    'name'?: string;
    /**
    * Identifies the resource this credential is associated with.
    */
    'resourceId'?: string;
    /**
    * Defaults to false
    */
    'expired'?: boolean;
    /**
    * The randomly generated SIP username for the credential.
    */
    'sipUsername'?: string;
    /**
    * The randomly generated SIP password for the credential.
    */
    'sipPassword'?: string;
    /**
    * ISO-8601 formatted date indicating when the resource was created.
    */
    'createdAt'?: string;
    /**
    * ISO-8601 formatted date indicating when the resource was updated.
    */
    'updatedAt'?: string;
    /**
    * ISO-8601 formatted date indicating when the resource will expire.
    */
    'expiresAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "string"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceId",
            "baseName": "resource_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "expired",
            "baseName": "expired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sipUsername",
            "baseName": "sip_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "sipPassword",
            "baseName": "sip_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TelephonyCredential.attributeTypeMap;
    }

    public constructor() {
    }
}

