/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Currency } from '../models/Currency.ts';
import { DateTimeObject } from '../models/DateTimeObject.ts';
import { Document } from '../models/Document.ts';
import { Image } from '../models/Image.ts';
import { Video } from '../models/Video.ts';
import { HttpFile } from '../http/http.ts';

/**
* Array containing the content of the message.
*/
export class TemplateParameters {
    /**
    * Describes the parameter type.
    */
    'type': TemplateParametersTypeEnum;
    'text'?: string;
    'currency'?: Currency;
    'dateTime'?: DateTimeObject;
    'image'?: Image;
    'document'?: Document;
    'video'?: Video;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TemplateParametersTypeEnum",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency",
            "format": ""
        },
        {
            "name": "dateTime",
            "baseName": "date_time",
            "type": "DateTimeObject",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "Image",
            "format": ""
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "Document",
            "format": ""
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "Video",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemplateParameters.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TemplateParametersTypeEnum = "text" | "currency" | "date_time" | "image" | "document" | "video" ;

