/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class TranscriptionPayloadTranscriptionData {
    /**
    * Speech recognition confidence level.
    */
    'confidence'?: number;
    /**
    * When false, it means that this is an interim result.
    */
    'isFinal'?: boolean;
    /**
    * Recognized text.
    */
    'transcript'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "number",
            "format": "double"
        },
        {
            "name": "isFinal",
            "baseName": "is_final",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "transcript",
            "baseName": "transcript",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TranscriptionPayloadTranscriptionData.attributeTypeMap;
    }

    public constructor() {
    }
}

