/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class UpdateFqdnRequest {
    /**
    * ID of the FQDN connection to which this IP should be attached.
    */
    'connectionId'?: string;
    /**
    * FQDN represented by this resource.
    */
    'fqdn'?: string;
    /**
    * Port to use when connecting to this FQDN.
    */
    'port'?: number | null;
    /**
    * The DNS record type for the FQDN. For cases where a port is not set, the DNS record type must be \'srv\'. For cases where a port is set, the DNS record type must be \'a\'. If the DNS record type is \'a\' and a port is not specified, 5060 will be used.
    */
    'dnsRecordType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "fqdn",
            "baseName": "fqdn",
            "type": "string",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number",
            "format": ""
        },
        {
            "name": "dnsRecordType",
            "baseName": "dns_record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateFqdnRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

