/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class UpdatePortingOrderRequirement {
    /**
    * identifies the document that satisfies this requirement
    */
    'fieldValue': string;
    /**
    * Identifies the requirement type that meets this requirement
    */
    'requirementTypeId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldValue",
            "baseName": "field_value",
            "type": "string",
            "format": ""
        },
        {
            "name": "requirementTypeId",
            "baseName": "requirement_type_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdatePortingOrderRequirement.attributeTypeMap;
    }

    public constructor() {
    }
}

