/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Campaign usecase. Must be of defined valid types. For more details, send a GET request to https://api.telnyx.com/10dlc/enum/usecase
 */
export enum Usecase {
    _2FA = '2FA',
    ACCOUNT_NOTIFICATION = 'ACCOUNT_NOTIFICATION',
    AGENTS_FRANCHISES = 'AGENTS_FRANCHISES',
    CARRIER_EXEMPT = 'CARRIER_EXEMPT',
    CHARITY = 'CHARITY',
    CONVERSATIONAL = 'CONVERSATIONAL',
    CUSTOMER_CARE = 'CUSTOMER_CARE',
    DELIVERY_NOTIFICATION = 'DELIVERY_NOTIFICATION',
    EMERGENCY = 'EMERGENCY',
    FRAUD_ALERT = 'FRAUD_ALERT',
    HIGHER_EDUCATION = 'HIGHER_EDUCATION',
    LOW_VOLUME = 'LOW_VOLUME',
    MARKETING = 'MARKETING',
    MANUFACTURING = 'MANUFACTURING',
    MIXED = 'MIXED',
    POLITICAL = 'POLITICAL',
    POLLING_VOTING = 'POLLING_VOTING',
    PUBLIC_SERVICE_ANNOUNCEMENT = 'PUBLIC_SERVICE_ANNOUNCEMENT',
    SECURITY_ALERT = 'SECURITY_ALERT',
    SOCIAL = 'SOCIAL',
    SWEEPSTAKE = 'SWEEPSTAKE',
    SOLE_PROPRIETOR = 'SOLE_PROPRIETOR',
    TRIAL = 'TRIAL',
}
