/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VerificationProfileRecordType } from '../models/VerificationProfileRecordType.ts';
import { VerifyProfileCallResponse } from '../models/VerifyProfileCallResponse.ts';
import { VerifyProfileFlashcallResponse } from '../models/VerifyProfileFlashcallResponse.ts';
import { VerifyProfilePSD2Response } from '../models/VerifyProfilePSD2Response.ts';
import { VerifyProfileSMSResponse } from '../models/VerifyProfileSMSResponse.ts';
import { VerifyProfileWhatsappResponse } from '../models/VerifyProfileWhatsappResponse.ts';
import { HttpFile } from '../http/http.ts';

export class VerifyProfileResponse {
    'id'?: string;
    'name'?: string;
    'webhookUrl'?: string;
    'webhookFailoverUrl'?: string;
    'recordType'?: VerificationProfileRecordType;
    'createdAt'?: string;
    'updatedAt'?: string;
    'sms'?: VerifyProfileSMSResponse;
    'psd2'?: VerifyProfilePSD2Response;
    'whatsapp'?: VerifyProfileWhatsappResponse;
    'call'?: VerifyProfileCallResponse;
    'flashcall'?: VerifyProfileFlashcallResponse;
    'language'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookFailoverUrl",
            "baseName": "webhook_failover_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "VerificationProfileRecordType",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "sms",
            "baseName": "sms",
            "type": "VerifyProfileSMSResponse",
            "format": ""
        },
        {
            "name": "psd2",
            "baseName": "psd2",
            "type": "VerifyProfilePSD2Response",
            "format": ""
        },
        {
            "name": "whatsapp",
            "baseName": "whatsapp",
            "type": "VerifyProfileWhatsappResponse",
            "format": ""
        },
        {
            "name": "call",
            "baseName": "call",
            "type": "VerifyProfileCallResponse",
            "format": ""
        },
        {
            "name": "flashcall",
            "baseName": "flashcall",
            "type": "VerifyProfileFlashcallResponse",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VerifyProfileResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



