/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VerifiedCallsDisplayProfileBusinessIdentity } from '../models/VerifiedCallsDisplayProfileBusinessIdentity.ts';
import { VerifiedCallsDisplayProfileCallReasonsInner } from '../models/VerifiedCallsDisplayProfileCallReasonsInner.ts';
import { VerifiedCallsDisplayProfilePhoneNumbersInner } from '../models/VerifiedCallsDisplayProfilePhoneNumbersInner.ts';
import { HttpFile } from '../http/http.ts';

export class VerifiedCallsDisplayProfile {
    'recordType'?: string;
    'id'?: string;
    /**
    * The Verified Calls Display Profile\'s name
    */
    'name'?: string;
    /**
    * The display name to be shown as the caller name in phones
    */
    'displayName'?: string;
    /**
    * The URL pointing to a public image file that will be displayed during calls in phones
    */
    'logoUrl'?: string;
    /**
    * The approval status of the Verified Calls Display Profile in Google
    */
    'status'?: VerifiedCallsDisplayProfileStatusEnum;
    'businessIdentity'?: VerifiedCallsDisplayProfileBusinessIdentity;
    'phoneNumbers'?: Array<VerifiedCallsDisplayProfilePhoneNumbersInner>;
    'callReasons'?: Array<VerifiedCallsDisplayProfileCallReasonsInner>;
    /**
    * An ISO 8601 datetime string for when the display profile was added to the Telnyx platform
    */
    'createdAt'?: string;
    /**
    * An ISO 8601 datetime string for when the display profile was updated
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "logoUrl",
            "baseName": "logo_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "VerifiedCallsDisplayProfileStatusEnum",
            "format": ""
        },
        {
            "name": "businessIdentity",
            "baseName": "business_identity",
            "type": "VerifiedCallsDisplayProfileBusinessIdentity",
            "format": ""
        },
        {
            "name": "phoneNumbers",
            "baseName": "phone_numbers",
            "type": "Array<VerifiedCallsDisplayProfilePhoneNumbersInner>",
            "format": ""
        },
        {
            "name": "callReasons",
            "baseName": "call_reasons",
            "type": "Array<VerifiedCallsDisplayProfileCallReasonsInner>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return VerifiedCallsDisplayProfile.attributeTypeMap;
    }

    public constructor() {
    }
}


export type VerifiedCallsDisplayProfileStatusEnum = "VERIFICATION_STATE_UNSPECIFIED" | "VERIFICATION_STATE_UNVERIFIED" | "VERIFICATION_STATE_PENDING" | "VERIFICATION_STATE_VERIFIED" | "VERIFICATION_STATE_SUSPENDED_IN_GMB" ;

