/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class VirtualCrossConnectRegion {
    /**
    * Identifies the resource.
    */
    'id'?: string;
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the resource was created.
    */
    'createdAt'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the resource was updated.
    */
    'updatedAt'?: string;
    /**
    * The region the interface is deployed to.
    */
    'regionCode'?: string;
    /**
    * The Virtual Private Cloud with which you would like to establish a cross connect.
    */
    'cloudProvider'?: VirtualCrossConnectRegionCloudProviderEnum;
    /**
    * The region where your Virtual Private Cloud hosts are located.
    */
    'cloudRegion'?: string;
    /**
    * The available throughput in Megabits per Second (Mbps) for your Virtual Cross Connect.
    */
    'bandwidthMbps'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "regionCode",
            "baseName": "region_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "cloudProvider",
            "baseName": "cloud_provider",
            "type": "VirtualCrossConnectRegionCloudProviderEnum",
            "format": ""
        },
        {
            "name": "cloudRegion",
            "baseName": "cloud_region",
            "type": "string",
            "format": ""
        },
        {
            "name": "bandwidthMbps",
            "baseName": "bandwidth_mbps",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirtualCrossConnectRegion.attributeTypeMap;
    }

    public constructor() {
    }
}


export type VirtualCrossConnectRegionCloudProviderEnum = "aws" | "azure" | "gce" ;

