/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class WhatsAppDetailRecord {
    /**
    * WhatsApp Message Id
    */
    'id'?: string;
    /**
    * WhatsApp API Version
    */
    'version'?: string;
    /**
    * WhatsApp Sender Id
    */
    'senderId'?: string;
    /**
    * WhatsApp Recipient Id
    */
    'recipientId'?: string;
    /**
    * WhatsApp Message Type. Consult WhatsApp API documentation to see all available types
    */
    'messageType'?: WhatsAppDetailRecordMessageTypeEnum;
    /**
    * WhatsApp Message Status. Consult WhatsApp API documentation to see all available status
    */
    'messageStatus'?: WhatsAppDetailRecordMessageStatusEnum;
    /**
    * Logical direction of the message from the Telnyx customer\'s perspective. It\'s inbound when the Telnyx customer receives the message, or outbound otherwise
    */
    'direction'?: WhatsAppDetailRecordDirectionEnum;
    /**
    * CLDR two-letter region-code of recipient
    */
    'recipientRegionCode'?: string;
    /**
    * Telnyx account currency used to describe monetary values, including billing cost
    */
    'currency'?: string;
    /**
    * A string representing Whatsapp error code. Consult WhatsApp API documentation to see all available error codes
    */
    'whatsappErrorCode'?: string;
    /**
    * UTC time when the message was created
    */
    'createdAt'?: Date;
    /**
    * UTC time when the webhook was received
    */
    'webhookReceivedAt'?: Date;
    /**
    * UUID representation of the webhook unique identifier
    */
    'webhookId'?: string;
    /**
    * Currency amount for Telnyx billing cost
    */
    'telnyxFee'?: string;
    /**
    * Currency amount for WhatsApp cost
    */
    'whatsappFee'?: string;
    /**
    * Whatsapp Conversation ID
    */
    'conversationId'?: string;
    /**
    * Whatsapp Conversation Origin
    */
    'conversationOrigin'?: WhatsAppDetailRecordConversationOriginEnum;
    /**
    * Whatsapp Business Account ID
    */
    'whatsappBusinessAccountId'?: string;
    'recordType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "senderId",
            "baseName": "sender_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientId",
            "baseName": "recipient_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "WhatsAppDetailRecordMessageTypeEnum",
            "format": ""
        },
        {
            "name": "messageStatus",
            "baseName": "message_status",
            "type": "WhatsAppDetailRecordMessageStatusEnum",
            "format": ""
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "WhatsAppDetailRecordDirectionEnum",
            "format": ""
        },
        {
            "name": "recipientRegionCode",
            "baseName": "recipient_region_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "whatsappErrorCode",
            "baseName": "whatsapp_error_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "webhookReceivedAt",
            "baseName": "webhook_received_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "webhookId",
            "baseName": "webhook_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "telnyxFee",
            "baseName": "telnyx_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "whatsappFee",
            "baseName": "whatsapp_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "conversationOrigin",
            "baseName": "conversation_origin",
            "type": "WhatsAppDetailRecordConversationOriginEnum",
            "format": ""
        },
        {
            "name": "whatsappBusinessAccountId",
            "baseName": "whatsapp_business_account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WhatsAppDetailRecord.attributeTypeMap;
    }

    public constructor() {
    }
}


export type WhatsAppDetailRecordMessageTypeEnum = "session" | "template" ;
export type WhatsAppDetailRecordMessageStatusEnum = "sent" | "delivered" | "read" | "failed" | "deleted" ;
export type WhatsAppDetailRecordDirectionEnum = "inbound" | "outbound" ;
export type WhatsAppDetailRecordConversationOriginEnum = "business_initiated" | "user_initiated" | "referral_conversion" ;

