/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Money } from '../models/Money.ts';
import { HttpFile } from '../http/http.ts';

export class WhatsAppUsageAggregation {
    'messageType'?: string;
    'direction'?: string;
    'status'?: string;
    'recipientCountryCode'?: string;
    'whatsappFee'?: Money;
    'telnyxFee'?: Money;
    'cost'?: Money;
    'count'?: string;
    'recordType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientCountryCode",
            "baseName": "recipient_country_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "whatsappFee",
            "baseName": "whatsapp_fee",
            "type": "Money",
            "format": ""
        },
        {
            "name": "telnyxFee",
            "baseName": "telnyx_fee",
            "type": "Money",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "Money",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WhatsAppUsageAggregation.attributeTypeMap;
    }

    public constructor() {
    }
}

