/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* The quality rating shows how messages from your template have been received by your customers in a rolling window of the past 24 hours. The possible values are provided by WhatsApp and are subject to change.
*/
export class WhatsappMessageTemplateQualityScore {
    'score'?: WhatsappMessageTemplateQualityScoreScoreEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "WhatsappMessageTemplateQualityScoreScoreEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WhatsappMessageTemplateQualityScore.attributeTypeMap;
    }

    public constructor() {
    }
}


export type WhatsappMessageTemplateQualityScoreScoreEnum = "UNKNOWN" | "HIGH" | "MEDIUM" | "LOW" ;

