/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WhatsappPhoneNumberWhatsappSettings } from '../models/WhatsappPhoneNumberWhatsappSettings.ts';
import { HttpFile } from '../http/http.ts';

export class WhatsappPhoneNumber {
    'recordType'?: string;
    'id'?: string;
    /**
    * The owning organization\'s ID
    */
    'organizationId'?: string;
    /**
    * The associated WhatsApp Business Account ID
    */
    'whatsappBusinessAccountId'?: string;
    /**
    * The configuration status for the phone number in the Telnyx platform
    */
    'status'?: WhatsappPhoneNumberStatusEnum;
    /**
    * The webhook url to be used by facebook
    */
    'webhookUrl'?: string;
    /**
    * The WhatsApp about section content
    */
    'about'?: string;
    /**
    * The phone number in E164 format
    */
    'phoneNumber'?: string;
    /**
    * The phone number\'s WhatsApp User ID, used in other Telnyx Whatsapp API endpoints
    */
    'whatsappUserId'?: string;
    'whatsappSettings'?: WhatsappPhoneNumberWhatsappSettings;
    /**
    * An ISO 8601 datetime string denoting when the account was added to the Telnyx platform
    */
    'createdAt'?: string;
    /**
    * An ISO 8601 datetime string for when the number order was updated.
    */
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "organizationId",
            "baseName": "organization_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "whatsappBusinessAccountId",
            "baseName": "whatsapp_business_account_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WhatsappPhoneNumberStatusEnum",
            "format": ""
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": "e164"
        },
        {
            "name": "whatsappUserId",
            "baseName": "whatsapp_user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "whatsappSettings",
            "baseName": "whatsapp_settings",
            "type": "WhatsappPhoneNumberWhatsappSettings",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return WhatsappPhoneNumber.attributeTypeMap;
    }

    public constructor() {
    }
}


export type WhatsappPhoneNumberStatusEnum = "pending" | "ready" | "disconnected" ;

