/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WhatsappMessageTemplateComponentsInner } from '../models/WhatsappMessageTemplateComponentsInner.ts';
import { WhatsappMessageTemplateQualityScore } from '../models/WhatsappMessageTemplateQualityScore.ts';
import { HttpFile } from '../http/http.ts';

export class WhatsappMessageTemplate {
    /**
    * Telnyx record type
    */
    'recordType'?: string;
    /**
    * The category of the message template, The possible values are provided by WhatsApp and are subject to change.
    */
    'category'?: WhatsappMessageTemplateCategoryEnum;
    /**
    * The components of the message template
    */
    'components'?: Array<WhatsappMessageTemplateComponentsInner>;
    /**
    * The id of the template on WhatsApp
    */
    'id'?: string;
    /**
    * The language of the message template, The available languages are provided by WhatsApp and are subject to change.
    */
    'language'?: WhatsappMessageTemplateLanguageEnum;
    /**
    * This name will act as an identifier grouping similar message templates together, the same name can be used to different languages.
    */
    'name'?: string;
    'qualityScore'?: WhatsappMessageTemplateQualityScore;
    'rejectedReason'?: string;
    /**
    * The current status of the message template, The possible values are provided by WhatsApp and are subject to change.
    */
    'status'?: WhatsappMessageTemplateStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "WhatsappMessageTemplateCategoryEnum",
            "format": ""
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<WhatsappMessageTemplateComponentsInner>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "bigint"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "WhatsappMessageTemplateLanguageEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "qualityScore",
            "baseName": "quality_score",
            "type": "WhatsappMessageTemplateQualityScore",
            "format": ""
        },
        {
            "name": "rejectedReason",
            "baseName": "rejected_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WhatsappMessageTemplateStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WhatsappMessageTemplate.attributeTypeMap;
    }

    public constructor() {
    }
}


export type WhatsappMessageTemplateCategoryEnum = "ACCOUNT_UPDATE" | "PAYMENT_UPDATE" | "PERSONAL_FINANCE_UPDATE" | "SHIPPING_UPDATE" | "RESERVATION_UPDATE" | "ISSUE_RESOLUTION" | "APPOINTMENT_UPDATE" | "TRANSPORTATION_UPDATE" | "TICKET_UPDATE" | "ALERT_UPDATE" | "AUTO_REPLY" ;
export type WhatsappMessageTemplateLanguageEnum = "af" | "sq" | "ar" | "az" | "bn" | "bg" | "ca" | "zh_CN" | "zh_HK" | "zh_TW" | "hr" | "cs" | "da" | "nl" | "en" | "en_GB" | "en_US" | "et" | "fil" | "fi" | "fr" | "ka" | "de" | "el" | "gu" | "ha" | "he" | "hi" | "hu" | "id" | "ga" | "it" | "ja" | "kn" | "kk" | "rw_RW" | "ko" | "ky_KG" | "lo" | "lv" | "lt" | "mk" | "ms" | "ml" | "mr" | "nb" | "fa" | "pl" | "pt_BR" | "pt_PT" | "pa" | "ro" | "ru" | "sr" | "sk" | "sl" | "es" | "es_AR" | "es_ES" | "es_MX" | "sw" | "sv" | "ta" | "te" | "th" | "tr" | "uk" | "ur" | "uz" | "vi" | "zu" ;
export type WhatsappMessageTemplateStatusEnum = "APPROVED" | "IN_APPEAL" | "PENDING" | "REJECTED" | "PENDING_DELETION" | "DELETED" | "DISABLED" ;

