/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* This object represents a wireless connectivity session log that happened through a SIM card. It aids in finding out potential problems when the SIM is not able to attach properly.
*/
export class WirelessConnectivityLog {
    'recordType'?: string;
    /**
    * Uniquely identifies the session.
    */
    'id'?: number;
    /**
    * The identification UUID of the related SIM card resource.
    */
    'simCardId'?: string;
    /**
    * The type of the session, \'registration\' being the initial authentication session and \'data\' the actual data transfer sessions.
    */
    'logType'?: WirelessConnectivityLogLogTypeEnum;
    /**
    * SIM cards are identified on their individual operator networks by a unique International Mobile Subscriber Identity (IMSI). <br/> Mobile network operators connect mobile phone calls and communicate with their market SIM cards using their IMSIs. The IMSI is stored in the Subscriber  Identity Module (SIM) inside the device and is sent by the device to the appropriate network. It is used to acquire the details of the device in the Home  Location Register (HLR) or the Visitor Location Register (VLR). 
    */
    'imsi'?: string;
    /**
    * The International Mobile Equipment Identity (or IMEI) is a number, usually unique, that identifies the device currently being used connect to the network.
    */
    'imei'?: string;
    /**
    * It\'s a three decimal digit that identifies a country.<br/><br/> This code is commonly seen joined with a Mobile Network Code (MNC) in a tuple that allows identifying a carrier known as PLMN (Public Land Mobile Network) code.
    */
    'mobileCountryCode'?: string;
    /**
    * It\'s a two to three decimal digits that identify a network.<br/><br/>  This code is commonly seen joined with a Mobile Country Code (MCC) in a tuple that allows identifying a carrier known as PLMN (Public Land Mobile Network) code.
    */
    'mobileNetworkCode'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the session started.
    */
    'startTime'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the session ended.
    */
    'stopTime'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the record was created.
    */
    'createdAt'?: string;
    /**
    * ISO 8601 formatted date-time indicating when the last heartbeat to the device was successfully recorded.
    */
    'lastSeen'?: string;
    /**
    * The Access Point Name (APN) identifies the packet data network that a mobile data user wants to communicate with.
    */
    'apn'?: string;
    /**
    * The SIM\'s address in the currently connected network. This IPv4 address is usually obtained dynamically, so it may vary according to the location or new connections. 
    */
    'ipv4'?: string;
    /**
    * The SIM\'s address in the currently connected network. This IPv6 address is usually obtained dynamically, so it may vary according to the location or new connections. 
    */
    'ipv6'?: string;
    /**
    * The radio technology the SIM card used during the session.
    */
    'radioAccessTechnology'?: string;
    /**
    * The state of the SIM card after when the session happened.
    */
    'state'?: string;
    /**
    * The cell ID to which the SIM connected.
    */
    'cellId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "simCardId",
            "baseName": "sim_card_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "logType",
            "baseName": "log_type",
            "type": "WirelessConnectivityLogLogTypeEnum",
            "format": ""
        },
        {
            "name": "imsi",
            "baseName": "imsi",
            "type": "string",
            "format": ""
        },
        {
            "name": "imei",
            "baseName": "imei",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobileCountryCode",
            "baseName": "mobile_country_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobileNetworkCode",
            "baseName": "mobile_network_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "stopTime",
            "baseName": "stop_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastSeen",
            "baseName": "last_seen",
            "type": "string",
            "format": ""
        },
        {
            "name": "apn",
            "baseName": "apn",
            "type": "string",
            "format": ""
        },
        {
            "name": "ipv4",
            "baseName": "ipv4",
            "type": "string",
            "format": ""
        },
        {
            "name": "ipv6",
            "baseName": "ipv6",
            "type": "string",
            "format": ""
        },
        {
            "name": "radioAccessTechnology",
            "baseName": "radio_access_technology",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "cellId",
            "baseName": "cell_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WirelessConnectivityLog.attributeTypeMap;
    }

    public constructor() {
    }
}


export type WirelessConnectivityLogLogTypeEnum = "registration" | "data" ;

