/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class WireguardPeer1 {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * ISO 8601 formatted date-time indicating when peer sent traffic last time.
    */
    'lastSeen'?: string;
    /**
    * The id of the wireguard interface associated with the peer.
    */
    'wireguardInterfaceId'?: string;
    /**
    * Your WireGuard `Interface.PrivateKey`.<br /><br />This attribute is only ever utlised if, on POST, you do NOT provide your own `public_key`. In which case, a new Public and Private key pair will be generated for you. When your `private_key` is returned, you must save this immediately as we do not save it within Telnyx. If you lose your Private Key, it can not be recovered.
    */
    'privateKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastSeen",
            "baseName": "last_seen",
            "type": "string",
            "format": ""
        },
        {
            "name": "wireguardInterfaceId",
            "baseName": "wireguard_interface_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "privateKey",
            "baseName": "private_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WireguardPeer1.attributeTypeMap;
    }

    public constructor() {
    }
}

