/**
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class WireguardInterface1 {
    /**
    * Identifies the type of the resource.
    */
    'recordType'?: string;
    /**
    * The Telnyx WireGuard peers `Peer.endpoint` value.
    */
    'endpoint'?: string;
    /**
    * The Telnyx WireGuard peers `Peer.PublicKey`.
    */
    'publicKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicKey",
            "baseName": "public_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WireguardInterface1.attributeTypeMap;
    }

    public constructor() {
    }
}

